# Noetfield local dev ports (high range — avoids 3000/8000/8001 conflicts)
export NF_DEV_WEB_PORT="${NF_DEV_WEB_PORT:-13000}"
export NF_DEV_PLATFORM_PORT="${NF_DEV_PLATFORM_PORT:-18001}"
export NF_DEV_GOV_API_PORT="${NF_DEV_GOV_API_PORT:-18002}"

export COGNITIVE_DASHBOARD_PORT="${COGNITIVE_DASHBOARD_PORT:-$NF_DEV_WEB_PORT}"
export PLATFORM_CONSOLE_PORT="${PLATFORM_CONSOLE_PORT:-$NF_DEV_PLATFORM_PORT}"
export COGNITIVE_DASHBOARD_API_PORT="${COGNITIVE_DASHBOARD_API_PORT:-$NF_DEV_GOV_API_PORT}"
