# Noetfield local dev ports (high range — avoids 3000/8000/8001 conflicts)
# Forward ONLY NF_DEV_PUBLIC_PORT (13080) in Cursor — unified proxy serves everything.
export NF_DEV_PUBLIC_PORT="${NF_DEV_PUBLIC_PORT:-13080}"
export NF_DEV_WWW_PORT="${NF_DEV_WWW_PORT:-13080}"
export NF_DEV_WEB_PORT="${NF_DEV_WEB_PORT:-13000}"
export NF_DEV_PLATFORM_PORT="${NF_DEV_PLATFORM_PORT:-8001}"
export NF_DEV_GOV_API_PORT="${NF_DEV_GOV_API_PORT:-18002}"
export NF_DEV_LEGACY_NEXT_PORT="${NF_DEV_LEGACY_NEXT_PORT:-3000}"

export WWW_DEV_PORT="${WWW_DEV_PORT:-$NF_DEV_WWW_PORT}"
export COGNITIVE_DASHBOARD_PORT="${COGNITIVE_DASHBOARD_PORT:-$NF_DEV_WEB_PORT}"
export PLATFORM_CONSOLE_PORT="${PLATFORM_CONSOLE_PORT:-$NF_DEV_PLATFORM_PORT}"
export COGNITIVE_DASHBOARD_API_PORT="${COGNITIVE_DASHBOARD_API_PORT:-$NF_DEV_GOV_API_PORT}"
