#!/usr/bin/env python3
"""Generate Cloudflare Pages _redirects from vercel.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERCEL = ROOT / "vercel.json"
OUT = ROOT / "_redirects"


def main() -> int:
    data = json.loads(VERCEL.read_text(encoding="utf-8"))
    lines: list[str] = [
        "# Generated by scripts/generate-cf-redirects.py — do not edit.",
    ]

    for rule in data.get("rewrites") or []:
        source = str(rule.get("source") or "").strip()
        dest = str(rule.get("destination") or "").strip()
        if source and dest:
            lines.append(f"{source} {dest} 200")

    for rule in data.get("redirects") or []:
        source = str(rule.get("source") or "").strip()
        dest = str(rule.get("destination") or "").strip()
        status = int(rule.get("statusCode") or 302)
        has_rules = rule.get("has") or []
        if has_rules:
            host = ""
            for item in has_rules:
                if isinstance(item, dict) and item.get("type") == "host":
                    host = str(item.get("value") or "")
            if host and dest:
                lines.append(f"https://{host}{source} {dest} {status}")
            continue
        if source and dest:
            lines.append(f"{source} {dest} {status}")

    text = "\n".join(lines) + "\n"
    if OUT.is_file() and OUT.read_text(encoding="utf-8") == text:
        print(f"ok unchanged {_redirects_name()}")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {_redirects_name()} ({len(lines) - 1} rules)")
    return 0


def _redirects_name() -> str:
    return "_redirects"


if __name__ == "__main__":
    raise SystemExit(main())
