#!/usr/bin/env python3
"""Generate Tier 1 WISE prompt pack (JSON + markdown). Single SSOT for v14 picker."""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from wise_prompt_lib import (  # noqa: E402
    FORBIDDEN_DEFAULT,
    W3_DEFAULT_CHAIN,
    W3_SIGNALS,
    build_wise_agent_prompt,
)

OUT_JSON = ROOT / "docs" / "ops" / "plans" / "tier1-smart.json"
OUT_MD = ROOT / "docs" / "ops" / "plans" / "TIER1_SMART_PROMPTS.md"
OUT_STATUS = ROOT / "docs" / "ops" / "plans" / "tier1-status.json"

FORBIDDEN_DEFAULT = FORBIDDEN_DEFAULT  # re-export for PROMPTS block

# fmt: off
PROMPTS = [
    # LAND
    {"id": "L-01", "phase": "LAND", "title": "Trust Brief conversion copy audit", "persona": "GRC", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": ["L-08", "L-14"],
     "task": "Audit /trust-brief/ against OFFERINGS_LOCKED ($10k, 6 weeks). PRS block, three SKUs only, CTA → /trust-brief/intake/. Regenerate via rebuild-www-v6.py if drift.",
     "verify": "curl -s localhost:13081/trust-brief/ | grep -F '$10,000'",
     "done_when": "Trust Brief page price, timeline, and CTA match commercial SSOT.",
     "stop_if": ["Price band changed without founder approval", "Fourth offering card added"],
     "context_budget": ["OFFERINGS_LOCKED.md", "docs/GTM_COPYBOOK.md", "scripts/rebuild-www-v6.py"],
     "success_reference": "Fixed-fee readiness SKU clarity"},
    {"id": "L-02", "phase": "LAND", "title": "Homepage §07–10 proof narrative", "persona": "CISO", "w3_signal": "www_proof", "effort": "M", "agent_mode": "cloud",
     "requires": [], "unblocks": ["L-12", "P-01"],
     "task": "Verify or implement homepage sections 07–10: pain moment, category zones (no vendor names), CCS stack ladder, FAQ. Regenerate index via rebuild-www-v6.py.",
     "verify": "grep -F 'The moment Copilot becomes auditable' www/index.html || grep -F 'Copilot becomes auditable' index.html",
     "done_when": "Homepage §07–10 present; no vendor comparison table on public www.",
     "stop_if": ["Vendor-named battle grid requested", "Hand-editing index.html without generator"],
     "context_budget": ["docs/WWW_V13_INSTITUTIONAL_100_PLAN_LOCKED_v1.md", "scripts/rebuild-www-v6.py", "scripts/verify-ui-e2e.sh"],
     "success_reference": "Numbered buyer narrative"},
    {"id": "L-03", "phase": "LAND", "title": "Trust center diligence hub", "persona": "Procurement", "w3_signal": "trust_diligence", "effort": "M", "agent_mode": "cloud",
     "requires": ["L-02"], "unblocks": ["L-04", "E-02"],
     "task": "Ensure /trust/ has honest cert table (Shipped/Orientation/Roadmap/N/A), metadata-only M365, fail-closed export copy. Link from footer + procurement.",
     "verify": "grep -F 'fail closed' trust/index.html",
     "done_when": "Trust center structurally matches procurement diligence pattern with honest scope rows.",
     "stop_if": ["SOC2 or ISO row marked Shipped without evidence", "Certifier fiction added"],
     "context_budget": ["docs/DESIGN_REFERENCE_GOALS_LOCKED_v1.md", "scripts/rebuild-www-v6.py", "trust/index.html"],
     "success_reference": "Trust center diligence structure"},
    {"id": "L-04", "phase": "LAND", "title": "Procurement pack → trust link", "persona": "Procurement", "w3_signal": "trust_diligence", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-03"], "unblocks": ["H-05"],
     "task": "/copilot/procurement/ links /trust/ and sample TLE. ZIP orientation only — no fake buyer logos.",
     "verify": "./scripts/verify-ui-e2e.sh 2>&1 | grep -i procurement || test -f copilot/procurement/index.html",
     "done_when": "Procurement page cross-links trust center and sample artifacts.",
     "stop_if": ["Fake customer logo wall", "ZIP contents invented without samples dir"],
     "context_budget": ["copilot/procurement/index.html", "docs/copilot/PROCUREMENT_ONE_PAGER.md"],
     "success_reference": "Procurement ZIP orientation"},
    {"id": "L-05", "phase": "LAND", "title": "Design partner scarcity copy", "persona": "Investor", "w3_signal": "design_partner", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": ["L-15"],
     "task": "Verify 'Accepting design partners' on /investors/ and /copilot/pilot/ — no fake logo wall or ARR.",
     "verify": "grep -F 'Accepting design partners' investors/index.html",
     "done_when": "Scarcity copy present; investor disclaimer intact.",
     "stop_if": ["Fake traction metrics", "Customer logos without signed release"],
     "context_budget": ["investors/index.html", "copilot/pilot/index.html", "docs/strategy/NOETFIELD_COMMERCIAL_SSOT_LOCKED_v1.md §5"],
     "success_reference": "Honest pre-revenue investor pages"},
    {"id": "L-06", "phase": "LAND", "title": "Investor 8-zone category map", "persona": "Investor", "w3_signal": "design_partner", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-05"], "unblocks": [],
     "task": "/investors/ category map: zones only, disclaimer 'not a compare page'. Align WWW v12 master map.",
     "verify": "grep -i 'not a compare' investors/index.html",
     "done_when": "Zone map live without vendor teardown language.",
     "stop_if": ["Named third-party vendor columns on public www"],
     "context_budget": ["docs/WWW_V13_INSTITUTIONAL_100_PLAN_LOCKED_v1.md", "scripts/rebuild-www-v6.py"],
     "success_reference": "Category positioning without vendor comparisons"},
    {"id": "L-07", "phase": "LAND", "title": "QuickScan anchor strip", "persona": "CIO", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": ["L-01"],
     "task": "Copilot QuickScan CAD 2–3.5K strip on /copilot/#quickscan — sub-tier A only per Worker Blueprint V3.",
     "verify": "grep -F 'quickscan' copilot/index.html -i",
     "done_when": "QuickScan tier visible with fixed-fee band; no fourth SKU.",
     "stop_if": ["New SKU tier beyond OFFERINGS_LOCKED"],
     "context_budget": ["docs/WORKER_BLUEPRINT_V3_NOETFIELD_COM_FULL_PROMPT.md", "OFFERINGS_LOCKED.md"],
     "success_reference": "Copilot QuickScan entry offer"},
    {"id": "L-08", "phase": "LAND", "title": "Intake RID threading", "persona": "Ops", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-01"], "unblocks": ["L-14"],
     "task": "All primary CTAs use data-rid-link; footer RID copy; trust-brief intake mailto includes RID.",
     "verify": "grep -r 'data-rid-link' www trust-brief gate --include='*.html' | head -3",
     "done_when": "RID threads from CTA through intake path.",
     "stop_if": ["Removing RID from primary conversion path"],
     "context_budget": ["assets/noetfield-shell.js", "trust-brief/intake/index.html"],
     "success_reference": "Ops traceability for design partner pipeline"},
    {"id": "L-09", "phase": "LAND", "title": "Federal ADM deadline chip", "persona": "GRC", "w3_signal": "channel_attach", "effort": "M", "agent_mode": "cloud",
     "requires": [], "unblocks": ["H-02", "H-04", "H-09"],
     "task": "/federal/ official canada.ca + TBS links above fold; AIA↔TLE preview table; 'not a federal certifier'.",
     "verify": "grep -F 'canada.ca' federal/index.html",
     "done_when": "Federal hub cites official sources; certifier disclaimer visible.",
     "stop_if": ["Claiming federal certification authority"],
     "context_budget": ["docs/FEDERAL_GOVERNANCE_PACK_v1.md", "scripts/rebuild-www-v6.py"],
     "success_reference": "TBS ADM orientation without certifier fiction"},
    {"id": "L-10", "phase": "LAND", "title": "MSP Phase 1→2 diagram", "persona": "MSP", "w3_signal": "channel_attach", "effort": "M", "agent_mode": "cloud",
     "requires": [], "unblocks": ["H-01", "H-07", "H-10"],
     "task": "/msp/ hero Readiness → Record; phase ladder; W3-MSP PASS line.",
     "verify": "grep -F 'Readiness → Record' msp/index.html",
     "done_when": "MSP two-tier RACI visible; no vendor names in Phase 1 copy.",
     "stop_if": ["Phase 1+2 collapsed into single SKU", "Vendor comparison page added"],
     "context_budget": ["docs/MSP_GOVERNANCE_PACK_v1.md", "scripts/rebuild-www-v6.py"],
     "success_reference": "MSP Phase 1 complement positioning"},
    {"id": "L-11", "phase": "LAND", "title": "Copilot CCS stack block", "persona": "CIO", "w3_signal": "www_proof", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-02"], "unblocks": ["E-01"],
     "task": "/copilot/ stack ladder references Learn.microsoft.com CCS — complement Purview, never replace.",
     "verify": "grep -F 'learn.microsoft.com' copilot/index.html",
     "done_when": "CCS complement ladder on copilot hub.",
     "stop_if": ["'Replace Purview' or anti-Microsoft positioning"],
     "context_budget": ["docs/GTM_COPYBOOK.md", "scripts/rebuild-www-v6.py"],
     "success_reference": "Microsoft stack complement lane"},
    {"id": "L-12", "phase": "LAND", "title": "FAQ alignment", "persona": "Procurement", "w3_signal": "www_proof", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-02"], "unblocks": [],
     "task": "/faq/ answers: not Purview replacement, three SKUs, no certifier — sync with homepage §10.",
     "verify": "grep -i 'purview' faq/index.html",
     "done_when": "FAQ matches homepage FAQ themes.",
     "stop_if": ["FAQ contradicts OFFERINGS_LOCKED"],
     "context_budget": ["faq/index.html", "scripts/rebuild-www-v6.py"],
     "success_reference": "Honest FAQ diligence pattern"},
    {"id": "L-13", "phase": "LAND", "title": "Enterprise offerings grid", "persona": "CISO", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "/enterprise/ uses nf-offerings-v5 three SKUs — retire nf-sku legacy markup.",
     "verify": "grep -F 'nf-offerings-v5' enterprise/index.html",
     "done_when": "Enterprise hub shows three locked SKUs only.",
     "stop_if": ["Bank Pilot presented as payment product"],
     "context_budget": ["enterprise/index.html", "OFFERINGS_LOCKED.md"],
     "success_reference": "Enterprise hub clarity"},
    {"id": "L-14", "phase": "LAND", "title": "Gate intake vectors", "persona": "Ops", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-08"], "unblocks": [],
     "task": "/gate/intake/ routes Trust Brief, Copilot, Bank Pilot, Partner with interest query params + RID mailto.",
     "verify": "grep -F 'interest=' gate/intake/index.html",
     "done_when": "Gate intake covers all commercial vectors.",
     "stop_if": ["New intake vector without offering lock update"],
     "context_budget": ["gate/intake/index.html", "OFFERINGS_LOCKED.md"],
     "success_reference": "Single intake router"},
    {"id": "L-15", "phase": "LAND", "title": "Design partner outreach batch", "persona": "Founder", "w3_signal": "design_partner", "effort": "M", "agent_mode": "hub",
     "requires": ["L-05"], "unblocks": ["E-20"],
     "task": "Agentic Hub: outreach batch per DESIGN_PARTNER_SOW_OUTLINE — max 5 contacts. NF-CLOUD: templates on disk only; never send email.",
     "verify": "test -f docs/copilot/DESIGN_PARTNER_SOW_OUTLINE.md",
     "done_when": "Outreach templates ready OR Hub logged 5 touches with YAML closeout.",
     "stop_if": ["NF-CLOUD sends email/calendar", "PII committed without consent"],
     "context_budget": ["docs/copilot/DESIGN_PARTNER_SOW_OUTLINE.md", "docs/ops/AGENTIC_COMMERCIAL_HANDOFF_v1.md"],
     "success_reference": "Land design partner pipeline"},
    # EXPAND
    {"id": "E-01", "phase": "EXPAND", "title": "5-minute demo script lock", "persona": "CISO", "w3_signal": "demo_live", "effort": "M", "agent_mode": "cloud",
     "requires": ["L-11"], "unblocks": ["E-05", "E-06", "E-07", "P-05"],
     "task": "Lock copilot/demo narrative: evaluate → confidence → Purview/Entra/audit → TLE → export. Workspace mock in hero. Demo ≤5 min on dev stack.",
     "verify": "./scripts/verify-ui-e2e.sh 2>&1 | grep -i demo || test -f copilot/demo/index.html",
     "done_when": "Demo script documented and e2e row passes or demo page complete.",
     "stop_if": ["Demo requires production M365 secrets", "Scope expands beyond metadata-only"],
     "context_budget": ["copilot/demo/index.html", "docs/strategy/NOETFIELD_COMMERCIAL_SSOT_LOCKED_v1.md §4", "scripts/verify-ui-e2e.sh"],
     "success_reference": "Receipt-first demo"},
    {"id": "E-02", "phase": "EXPAND", "title": "TLE verify walkthrough", "persona": "GRC", "w3_signal": "tle_artifact", "effort": "M", "agent_mode": "cloud",
     "requires": ["L-03"], "unblocks": ["E-03"],
     "task": "/trust-ledger/verify/ documents tamper FAIL path. Link from /trust/ and samples. No Ed25519 claim until shipped.",
     "verify": "grep -i 'tamper\\|fail' trust-ledger/verify/index.html",
     "done_when": "Verify page explains fail-closed export check.",
     "stop_if": ["Claiming crypto not in PRODUCT_TRUTH"],
     "context_budget": ["trust-ledger/verify/index.html", "PRODUCT_TRUTH.md"],
     "success_reference": "Export verify walkthrough"},
    {"id": "E-03", "phase": "EXPAND", "title": "TLE YAML samples trio", "persona": "Procurement", "w3_signal": "tle_artifact", "effort": "M", "agent_mode": "cloud",
     "requires": ["E-02"], "unblocks": ["E-04", "L-04"],
     "task": "samples: go, conditional, rejected + README for procurement. Optional tampered fail example.",
     "verify": "ls samples/tle/*.yaml 2>/dev/null | wc -l | grep -qv '^0$' || ls trust-ledger/samples/ 2>/dev/null",
     "done_when": "Three verdict samples + README exist for diligence.",
     "stop_if": ["Inventing customer-specific TLE content"],
     "context_budget": ["trust-ledger/samples/", "docs/spec/examples/"],
     "success_reference": "Procurement-ready sample pack"},
    {"id": "E-04", "phase": "EXPAND", "title": "Export manifest JSON spec", "persona": "Engineering", "w3_signal": "export_e2e", "effort": "S", "agent_mode": "cloud",
     "requires": ["E-03"], "unblocks": ["E-05", "E-06"],
     "task": "Document sidecar manifest: tle_id, export_integrity, hashes — docs/api or trust-ledger.",
     "verify": "grep -i 'export_integrity' docs/api/index.html trust-ledger/index.html 2>/dev/null | head -1",
     "done_when": "Manifest fields documented for integrators.",
     "stop_if": ["New API route without pilot need"],
     "context_budget": ["docs/api/index.html", "docs/spec/"],
     "success_reference": "Evidence manifest clarity"},
    {"id": "E-05", "phase": "EXPAND", "title": "Board PDF path E2E", "persona": "GRC", "w3_signal": "export_e2e", "effort": "L", "agent_mode": "cloud",
     "requires": ["E-01", "E-04"], "unblocks": [],
     "task": "Workspace TLE detail exposes Board pack (PDF). verify-ui-e2e dashboard chunk asserts link.",
     "verify": "./scripts/verify-ui-e2e.sh 2>&1 | grep -i 'board\\|pdf' || echo 'run full e2e with dev stack'",
     "done_when": "Board PDF export reachable from workspace TLE detail — **W3 critical path**.",
     "stop_if": ["PDF generation requires founder-only prod keys", "Fake PDF without export pipeline"],
     "context_budget": ["scripts/verify-ui-e2e.sh", "workspace/", "services/"],
     "success_reference": "Board PDF in governance meeting — W3 bar"},
    {"id": "E-06", "phase": "EXPAND", "title": "Procurement ZIP path E2E", "persona": "Procurement", "w3_signal": "export_e2e", "effort": "L", "agent_mode": "cloud",
     "requires": ["E-01", "E-04"], "unblocks": [],
     "task": "Workspace TLE detail exposes Procurement pack (ZIP). Same e2e coverage as board PDF.",
     "verify": "./scripts/verify-ui-e2e.sh 2>&1 | grep -i 'procurement\\|zip' || make procurement-pack-e2e",
     "done_when": "Procurement ZIP export reachable — **W3 critical path**.",
     "stop_if": ["ZIP contents not tied to real export service"],
     "context_budget": ["scripts/verify-ui-e2e.sh", "Makefile"],
     "success_reference": "Diligence ZIP path"},
    {"id": "E-07", "phase": "EXPAND", "title": "Confidence score on result page", "persona": "CISO", "w3_signal": "workspace_path", "effort": "S", "agent_mode": "cloud",
     "requires": ["E-01"], "unblocks": [],
     "task": "/evaluate → /result/{rid} shows Confidence score badge — fix if regressed.",
     "verify": "grep -ri 'confidence' result/ evaluate/ workspace/ --include='*.html' 2>/dev/null | head -1",
     "done_when": "Confidence visible on result flow.",
     "stop_if": ["Changing score algorithm without spec update"],
     "context_budget": ["scripts/verify-ui-e2e.sh", "result/"],
     "success_reference": "Evaluate loop buyer clarity"},
    {"id": "E-08", "phase": "EXPAND", "title": "M365 connector mock OAuth", "persona": "CIO", "w3_signal": "workspace_path", "effort": "M", "agent_mode": "cloud",
     "requires": [], "unblocks": ["E-01"],
     "task": "/workspace/connectors mock OAuth → workspace banner. e2e green.",
     "verify": "./scripts/verify-ui-e2e.sh 2>&1 | grep -i connector || test -d workspace/connectors",
     "done_when": "Mock connector flow completes without real tenant.",
     "stop_if": ["Real Azure AD secrets in repo", "OAuth to production without customer"],
     "context_budget": ["workspace/connectors/", "scripts/verify-ui-e2e.sh"],
     "success_reference": "Metadata-only M365 path"},
    {"id": "E-09", "phase": "EXPAND", "title": "API decision semantics", "persona": "Engineering", "w3_signal": "tle_artifact", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "docs/api/index.html: allow≈201, review≈202, deny≈403 orientation paragraph.",
     "verify": "grep -E '201|202|403' docs/api/index.html",
     "done_when": "HTTP semantics documented for integrators.",
     "stop_if": ["OpenAPI drift without implementation check"],
     "context_budget": ["docs/api/index.html"],
     "success_reference": "Clear API contract orientation"},
    {"id": "E-10", "phase": "EXPAND", "title": "Governance console deep link", "persona": "CISO", "w3_signal": "workspace_path", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "/console/ primary CTA resolves to pilot host; shadow mode copy correct.",
     "verify": "grep -i 'shadow' console/index.html",
     "done_when": "Console CTA and shadow copy accurate.",
     "stop_if": ["Console claims execution rights Noetfield lacks"],
     "context_budget": ["console/index.html"],
     "success_reference": "Read-only governance console"},
    {"id": "E-11", "phase": "EXPAND", "title": "Copilot pilot success signals", "persona": "CISO", "w3_signal": "design_partner", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-05"], "unblocks": [],
     "task": "/copilot/pilot/ lists Wk 0–12 path aligned with commercial SSOT §90-day.",
     "verify": "grep -i 'week' copilot/pilot/index.html",
     "done_when": "Pilot timeline matches design partner program.",
     "stop_if": ["Timeline promises without SOW alignment"],
     "context_budget": ["copilot/pilot/index.html", "docs/strategy/NOETFIELD_COMMERCIAL_SSOT_LOCKED_v1.md §5"],
     "success_reference": "90-day design partner path"},
    {"id": "E-12", "phase": "EXPAND", "title": "Trust Ledger hub", "persona": "GRC", "w3_signal": "tle_artifact", "effort": "S", "agent_mode": "cloud",
     "requires": ["E-02"], "unblocks": [],
     "task": "/trust-ledger/ links workspace + samples + verify.",
     "verify": "grep -i 'verify\\|sample' trust-ledger/index.html",
     "done_when": "TLE hub is single spine for product + docs.",
     "stop_if": ["TLE SaaS checkout added"],
     "context_budget": ["trust-ledger/index.html"],
     "success_reference": "TLE product hub"},
    {"id": "E-13", "phase": "EXPAND", "title": "Bank Pilot shadow scope", "persona": "CISO", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "/bank-pilot/ read-only, no custody — OFFERINGS_LOCKED alignment.",
     "verify": "grep -i 'read-only\\|no custody' bank-pilot/index.html enterprise/index.html 2>/dev/null | head -1",
     "done_when": "Bank pilot scope honest on www.",
     "stop_if": ["Payment/custody claims on Noetfield www"],
     "context_budget": ["bank-pilot/index.html", "OFFERINGS_LOCKED.md"],
     "success_reference": "Shadow simulation positioning"},
    {"id": "E-14", "phase": "EXPAND", "title": "SME pack lane", "persona": "GRC", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "/copilot/sme/ same TLE spine, SME pricing orientation — no enterprise platform claims.",
     "verify": "test -f copilot/sme/index.html",
     "done_when": "SME lane live with governance-first copy.",
     "stop_if": ["Full GRC platform breadth claims"],
     "context_budget": ["copilot/sme/index.html", "docs/strategy/NOETFIELD_SME_PROVIDER_BLUEPRINT_LOCKED_v1.md"],
     "success_reference": "SME provider grade pack"},
    {"id": "E-15", "phase": "EXPAND", "title": "Receipt mock consistency", "persona": "Design", "w3_signal": "www_proof", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-02"], "unblocks": [],
     "task": "All GTM hubs: nf-receipt-mock with export_integrity PASS via generator receipt() helper.",
     "verify": "grep -r 'export_integrity' --include='*.html' copilot trust-brief federal msp 2>/dev/null | head -3",
     "done_when": "Receipt mocks consistent across hubs.",
     "stop_if": ["Hand-editing receipt HTML per page"],
     "context_budget": ["scripts/rebuild-www-v6.py"],
     "success_reference": "Receipt visual consistency"},
    {"id": "E-16", "phase": "EXPAND", "title": "Stat bar consistency", "persona": "Design", "w3_signal": "www_proof", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "Homepage stat bar: 4 · $10k · 90d · 3 SKUs — no fake analyst stats.",
     "verify": "grep -F '90' index.html | head -1",
     "done_when": "Stat bar matches commercial facts.",
     "stop_if": ["Third-party analyst stats without citation"],
     "context_budget": ["scripts/rebuild-www-v6.py", "index.html"],
     "success_reference": "Honest metrics bar"},
    {"id": "E-17", "phase": "EXPAND", "title": "Mega CTA every hub", "persona": "Design", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "Every hub ends nf-cta-mega — Request Governance Brief + secondary.",
     "verify": "grep -r 'nf-cta-mega' --include='*.html' copilot federal msp enterprise trust-brief 2>/dev/null | wc -l",
     "done_when": "Mega CTA on all primary hubs.",
     "stop_if": ["CTA points off-domain without approval"],
     "context_budget": ["scripts/rebuild-www-v6.py"],
     "success_reference": "Conversion spine"},
    {"id": "E-18", "phase": "EXPAND", "title": "Shell v13 bump", "persona": "Ops", "w3_signal": "ship_green", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": ["P-01"],
     "task": "SHELL_VERSION and ?v=13 on all regenerated pages after www changes.",
     "verify": "grep 'SHELL_VERSION' assets/noetfield-shell.js && ./scripts/verify-static-www.sh",
     "done_when": "Shell version bumped coherently.",
     "stop_if": ["Partial bump leaving cache stale on key hubs"],
     "context_budget": ["assets/noetfield-shell.js", "scripts/rebuild-www-v6.py"],
     "success_reference": "Cache-coherent deploy"},
    {"id": "E-19", "phase": "EXPAND", "title": "Honest scope badges every hub", "persona": "Procurement", "w3_signal": "trust_diligence", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-03"], "unblocks": [],
     "task": "scope_block() on hubs: Shipped/Orientation/Roadmap/N/A — no certifier rows as Shipped.",
     "verify": "grep -r 'Shipped\\|Orientation' --include='*.html' copilot federal msp 2>/dev/null | head -3",
     "done_when": "Scope badges honest on hubs.",
     "stop_if": ["Marking roadmap items as shipped"],
     "context_budget": ["scripts/rebuild-www-v6.py", "docs/DESIGN_REFERENCE_GOALS_LOCKED_v1.md"],
     "success_reference": "Honest scope tables"},
    {"id": "E-20", "phase": "EXPAND", "title": "Buyer debrief after call", "persona": "Founder", "w3_signal": "design_partner", "effort": "S", "agent_mode": "hub",
     "requires": ["L-15"], "unblocks": [],
     "task": "After CIO call: debrief YAML — pain, Copilot timeline, next step Trust Brief vs pilot. Cloud stores template only.",
     "verify": "mkdir -p docs/copilot/debriefs && test -d docs/copilot/debriefs",
     "done_when": "Debrief template or one sanitized example on disk.",
     "stop_if": ["Customer PII in committed debrief without redaction"],
     "context_budget": ["docs/copilot/DESIGN_PARTNER_PIPELINE_v1.md"],
     "success_reference": "Pipeline intelligence capture"},
    # CHANNEL
    {"id": "H-01", "phase": "CHANNEL", "title": "MSP READINESS→RECORD mapping UX", "persona": "MSP", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-10"], "unblocks": [],
     "task": "/msp/ links READINESS_TO_RECORD_MAPPING_v1.md; partner intake CTA.",
     "verify": "grep -i 'READINESS\\|mapping' msp/index.html docs/msp/*.md 2>/dev/null | head -1",
     "done_when": "MSP mapping doc linked from hub.",
     "stop_if": ["MSP page claims Phase 1 execution for Noetfield"],
     "context_budget": ["msp/index.html", "docs/msp/"],
     "success_reference": "Two-tier MSP attach"},
    {"id": "H-02", "phase": "CHANNEL", "title": "Federal AIA mapping doc link", "persona": "GRC", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-09"], "unblocks": [],
     "task": "Prominent AIA_TLE_MAPPING_v1.md link from federal proof grid.",
     "verify": "grep -i 'AIA' federal/index.html",
     "done_when": "AIA mapping accessible from federal hub.",
     "stop_if": ["Claiming AIA certification"],
     "context_budget": ["federal/index.html", "docs/federal/"],
     "success_reference": "GC AIA attach"},
    {"id": "H-03", "phase": "CHANNEL", "title": "Partner gateway", "persona": "MSP", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": ["H-06"],
     "task": "/partners/ API + MSP links; no MSB as primary hero.",
     "verify": "test -f partners/index.html && grep -vi 'MSB' partners/index.html | head -1",
     "done_when": "Partner gateway orients MSP/API — not payments.",
     "stop_if": ["MSB hero on Noetfield partners page"],
     "context_budget": ["partners/index.html"],
     "success_reference": "Partner entry point"},
    {"id": "H-04", "phase": "CHANNEL", "title": "GC Copilot PIN checklist", "persona": "GRC", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-09"], "unblocks": [],
     "task": "PIN checklist doc linked from federal; scope badges in hero.",
     "verify": "grep -i 'PIN\\|checklist' federal/index.html docs/federal/ 2>/dev/null | head -1",
     "done_when": "PIN checklist discoverable from federal hub.",
     "stop_if": [],
     "context_budget": ["federal/index.html", "docs/federal/"],
     "success_reference": "GC Copilot readiness"},
    {"id": "H-05", "phase": "CHANNEL", "title": "NIST strip on procurement", "persona": "Procurement", "w3_signal": "trust_diligence", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-04"], "unblocks": [],
     "task": "Procurement ZIP citations mention NIST AI RMF — orientation only.",
     "verify": "grep -i 'NIST' copilot/procurement/index.html docs/copilot/PROCUREMENT_ONE_PAGER.md 2>/dev/null | head -1",
     "done_when": "NIST orientation in procurement copy.",
     "stop_if": ["Claiming NIST certification"],
     "context_budget": ["docs/references/GOVERNANCE_SOURCES_HANDBOOK_LOCKED_v1.md"],
     "success_reference": "Framework citation discipline"},
    {"id": "H-06", "phase": "CHANNEL", "title": "Partner LOI template", "persona": "MSP", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "cloud",
     "requires": ["H-03"], "unblocks": [],
     "task": "docs/msp/ or docs/partners/ LOI orientation — not legal advice.",
     "verify": "ls docs/msp/*LOI* docs/partners/*LOI* 2>/dev/null | head -1",
     "done_when": "LOI orientation doc exists.",
     "stop_if": ["Presenting template as legal counsel"],
     "context_budget": ["docs/msp/", "docs/partners/"],
     "success_reference": "Partner LOI orientation"},
    {"id": "H-07", "phase": "CHANNEL", "title": "Wholesale pricing orientation", "persona": "MSP", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-10"], "unblocks": [],
     "task": "MSP Governance Pack $2k–10k via partner — one paragraph on /msp/.",
     "verify": "grep -E '2[, ]?000|10[, ]?000' msp/index.html",
     "done_when": "Wholesale band visible on MSP hub.",
     "stop_if": ["Pricing outside OFFERINGS_LOCKED bands"],
     "context_budget": ["msp/index.html", "OFFERINGS_LOCKED.md"],
     "success_reference": "MSP wholesale clarity"},
    {"id": "H-08", "phase": "CHANNEL", "title": "Phase 1 complement copy", "persona": "MSP", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-10"], "unblocks": [],
     "task": "MSP page: Phase 1 examples generic — no third-party vendor names.",
     "verify": "grep -i 'phase 1' msp/index.html",
     "done_when": "Phase 1 complement copy without vendor teardown.",
     "stop_if": ["Named third-party vendor on public MSP page"],
     "context_budget": ["msp/index.html"],
     "success_reference": "Generic Phase 1 complement"},
    {"id": "H-09", "phase": "CHANNEL", "title": "Federal intake query param", "persona": "GRC", "w3_signal": "intake_conversion", "effort": "S", "agent_mode": "cloud",
     "requires": ["L-09", "L-14"], "unblocks": [],
     "task": "/trust-brief/intake/?interest=federal linked from federal hub.",
     "verify": "grep -F 'interest=federal' federal/index.html trust-brief/intake/index.html 2>/dev/null | head -1",
     "done_when": "Federal interest param wired.",
     "stop_if": [],
     "context_budget": ["federal/index.html", "trust-brief/intake/index.html"],
     "success_reference": "Federal intake vector"},
    {"id": "H-10", "phase": "CHANNEL", "title": "MSP partner conversation script", "persona": "Founder", "w3_signal": "channel_attach", "effort": "S", "agent_mode": "hub",
     "requires": ["L-10"], "unblocks": [],
     "task": "Hub: first MSP partner call script — Phase 2 attach after readiness vendor.",
     "verify": "test -f docs/msp/ || mkdir -p docs/msp",
     "done_when": "MSP call script on disk for Hub use.",
     "stop_if": ["NF-CLOUD places partner calls"],
     "context_budget": ["docs/MSP_GOVERNANCE_PACK_v1.md"],
     "success_reference": "MSP channel playbook"},
    # PROVE
    {"id": "P-01", "phase": "PROVE", "title": "verify-ui-e2e www v12", "persona": "Ops", "w3_signal": "ship_green", "effort": "M", "agent_mode": "cloud",
     "requires": ["L-02", "E-18"], "unblocks": ["P-03"],
     "task": "Extend and run verify-ui-e2e.sh for §07–10, /trust/, federal, msp, copilot CCS rows.",
     "verify": "./scripts/verify-ui-e2e.sh",
     "done_when": "Static www v12 e2e rows green.",
     "stop_if": ["Fixing e2e by weakening assertions"],
     "context_budget": ["scripts/verify-ui-e2e.sh"],
     "success_reference": "Receipt-first www proof"},
    {"id": "P-02", "phase": "PROVE", "title": "rebuild-www-v6 single source", "persona": "Ops", "w3_signal": "ship_green", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": ["P-01"],
     "task": "Hand-edited GTM HTML forbidden — generator only. Migrate stragglers into rebuild-www-v6.py.",
     "verify": "python3 scripts/rebuild-www-v6.py && git diff --stat | head -5",
     "done_when": "GTM pages regenerate cleanly from generator.",
     "stop_if": ["Large unrelated refactor in generator"],
     "context_budget": ["scripts/rebuild-www-v6.py"],
     "success_reference": "Single www SSOT"},
    {"id": "P-03", "phase": "PROVE", "title": "plan-with-no-asf-verify", "persona": "Ops", "w3_signal": "ship_green", "effort": "S", "agent_mode": "cloud",
     "requires": ["P-01"], "unblocks": ["P-04"],
     "task": "./scripts/plan-with-no-asf-verify.sh green after ship.",
     "verify": "./scripts/plan-with-no-asf-verify.sh",
     "done_when": "Plan verify bundle passes.",
     "stop_if": ["Skipping verify to ship faster"],
     "context_budget": ["scripts/plan-with-no-asf-verify.sh"],
     "success_reference": "Ship gate green"},
    {"id": "P-04", "phase": "PROVE", "title": "sync-prompt-pack-status", "persona": "Ops", "w3_signal": "ship_green", "effort": "S", "agent_mode": "cloud",
     "requires": [], "unblocks": [],
     "task": "After done prompts: sync registry + QUICK_PICK + tier1-status.json.",
     "verify": "python3 scripts/sync-tier1-status.py --dry-run 2>/dev/null || python3 scripts/sync-prompt-pack-status.py",
     "done_when": "Status files reflect completed Tier 1 ids.",
     "stop_if": [],
     "context_budget": ["scripts/sync-prompt-pack-status.py", "docs/ops/plans/tier1-status.json"],
     "success_reference": "Ops hygiene"},
    {"id": "P-05", "phase": "PROVE", "title": "Staging smoke / demo URL", "persona": "Ops", "w3_signal": "demo_live", "effort": "M", "agent_mode": "cloud",
     "requires": ["E-01"], "unblocks": [],
     "task": "Public demo URL documented in os/SHIP_NOW when staging live.",
     "verify": "grep -i 'demo\\|13081\\|staging' os/SHIP_NOW.md | head -3",
     "done_when": "Demo URL in SHIP_NOW for founder outreach.",
     "stop_if": ["Deploying prod without founder approval"],
     "context_budget": ["os/SHIP_NOW.md", "Makefile"],
     "success_reference": "Week 0–2 commercial SSOT milestone"},
]
# fmt: on


def main() -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    enriched = []
    for p in PROMPTS:
        entry = dict(p)
        entry["forbidden"] = FORBIDDEN_DEFAULT
        entry["agent_prompt"] = build_wise_agent_prompt(p)
        entry["w3_signal_label"] = W3_SIGNALS.get(p["w3_signal"], p["w3_signal"])
        enriched.append(entry)

    pack = {
        "version": "v14-wise",
        "generated_at": now,
        "count": len(enriched),
        "framework": "WISE (Witness · Intent · Scope · Evidence)",
        "w3_north_star": "Board PDF in governance meeting OR deposit ≥ CAD 2K / signed LOI",
        "max_per_session": 1,
        "default_chain": W3_DEFAULT_CHAIN,
        "critical_path": ["E-01", "E-04", "E-05", "E-06", "L-03", "P-01"],
        "prompts": enriched,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(pack, indent=2) + "\n", encoding="utf-8")

    # Status file — preserve done ids if exists
    done_ids: set[str] = set()
    if OUT_STATUS.is_file():
        try:
            st = json.loads(OUT_STATUS.read_text(encoding="utf-8"))
            done_ids = {k for k, v in st.get("status", {}).items() if v == "done"}
        except json.JSONDecodeError:
            pass
    status = {
        "version": "v14-wise",
        "updated_at": now,
        "status": {p["id"]: ("done" if p["id"] in done_ids else "backlog") for p in enriched},
    }
    OUT_STATUS.write_text(json.dumps(status, indent=2) + "\n", encoding="utf-8")

    md = [
        "# Tier 1 WISE Prompts (generated)",
        "",
        f"_Generated {now} by `scripts/generate-tier1-smart-pack.py` · framework: WISE_",
        "",
        "**Picker:** `python3 scripts/pick-wise.py --prompt` (auto maturity + bottleneck)",
        "",
        "**SSOT:** [NOETFIELD_PROMPT_PACK_V14_WISE_LOCKED_v1.md](../NOETFIELD_PROMPT_PACK_V14_WISE_LOCKED_v1.md)",
        "",
    ]
    for p in enriched:
        md.extend([
            f"---",
            f"",
            f"## {p['id']} · {p['title']}",
            f"",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| Phase | {p['phase']} |",
            f"| Persona | {p['persona']} |",
            f"| W3 signal | {p['w3_signal_label']} |",
            f"| Requires | {', '.join(p['requires']) or '—'} |",
            f"| Unblocks | {', '.join(p['unblocks']) or '—'} |",
            f"",
            p["agent_prompt"],
            f"",
        ])
    OUT_MD.write_text("\n".join(md), encoding="utf-8")
    print(f"Wrote {OUT_JSON} ({len(enriched)} prompts)")
    print(f"Wrote {OUT_STATUS}")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
