#!/usr/bin/env python3
"""Generate Cloudflare Pages _middleware.js (denylist + optional gov sandbox proxy)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DENYLIST = ROOT / "governance" / "PUBLIC_OUTPUT_DENYLIST.json"
PROXY_CFG = ROOT / "data" / "nf-www-gov-proxy-v1.json"
OUT = ROOT / "functions" / "_middleware.js"

# Prefixes proxied to Railway when nf-www-gov-proxy-v1.enabled=true (middleware, not _redirects).
GOV_PROXY_PREFIXES = (
    "/workspace",
    "/tle",
    "/connectors",
    "/audit",
    "/evidence",
    "/api/v1/sandbox",
)


def _deny_sets(data: dict) -> tuple[list[str], list[str]]:
    exact = list(dict.fromkeys(str(p) for p in data.get("exact_paths", [])))
    prefixes = list(dict.fromkeys(str(p) for p in data.get("prefix_paths", [])))
    return exact, prefixes


def _gov_proxy_block() -> tuple[bool, dict[str, str]]:
    if not PROXY_CFG.is_file():
        return False, {}
    try:
        cfg = json.loads(PROXY_CFG.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return False, {}
    if not cfg.get("enabled"):
        return False, {}
    web = str(cfg.get("gov_web_origin") or "").rstrip("/")
    api = str(cfg.get("gov_api_origin") or "").rstrip("/")
    if not web or not api:
        return False, {}
    origins: dict[str, str] = {}
    for prefix in GOV_PROXY_PREFIXES:
        origins[prefix] = web if prefix == "/workspace" else api
    return True, origins


def main() -> int:
    data = json.loads(DENYLIST.read_text(encoding="utf-8"))
    exact, prefixes = _deny_sets(data)
    exact_json = json.dumps(exact, separators=(",", ":"))
    prefix_json = json.dumps(prefixes, separators=(",", ":"))
    proxy_enabled, proxy_origins = _gov_proxy_block()
    proxy_json = json.dumps(
        {"enabled": proxy_enabled, "origins": proxy_origins},
        separators=(",", ":"),
    )

    source = f"""// Generated by scripts/generate-www-deny-middleware.py — do not edit.
const EXACT = new Set({exact_json});
const PREFIXES = {prefix_json};
const GOV_PROXY = {proxy_json};

function isDenied(pathname) {{
  if (EXACT.has(pathname)) return true;
  for (const raw of PREFIXES) {{
    const base = raw.endsWith("/") ? raw.slice(0, -1) : raw;
    if (pathname === base || pathname === raw) return true;
    const withSlash = raw.endsWith("/") ? raw : `${{raw}}/`;
    if (pathname.startsWith(withSlash)) return true;
  }}
  return false;
}}

function matchGovProxy(pathname) {{
  if (!GOV_PROXY.enabled) return null;
  const sorted = Object.keys(GOV_PROXY.origins).sort((a, b) => b.length - a.length);
  for (const prefix of sorted) {{
    if (pathname === prefix || pathname.startsWith(`${{prefix}}/`)) {{
      return {{ prefix, origin: GOV_PROXY.origins[prefix] }};
    }}
  }}
  return null;
}}

async function proxyGovRequest(context, match) {{
  const req = context.request;
  const url = new URL(req.url);
  const target = new URL(url.pathname + url.search, match.origin);
  const headers = new Headers(req.headers);
  headers.delete("host");
  const init = {{ method: req.method, headers, redirect: "manual" }};
  if (req.method !== "GET" && req.method !== "HEAD") {{
    init.body = req.body;
  }}
  return fetch(target.toString(), init);
}}

export async function onRequest(context) {{
  const pathname = new URL(context.request.url).pathname;
  const gov = matchGovProxy(pathname);
  if (gov) {{
    return proxyGovRequest(context, gov);
  }}

  if (!isDenied(pathname)) {{
    return context.next();
  }}

  const notFoundUrl = new URL("/404.html", context.request.url);
  if (context.env?.ASSETS?.fetch) {{
    const asset = await context.env.ASSETS.fetch(notFoundUrl);
    if (asset && asset.ok) {{
      return new Response(asset.body, {{
        status: 404,
        headers: {{
          "content-type": asset.headers.get("content-type") || "text/html; charset=utf-8",
          "cache-control": "no-store",
        }},
      }});
    }}
  }}

  return new Response("Not found", {{
    status: 404,
    headers: {{ "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" }},
  }});
}}
"""

    if OUT.is_file() and OUT.read_text(encoding="utf-8") == source:
        print("ok unchanged functions/_middleware.js")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(source, encoding="utf-8")
    proxy_note = f"gov_proxy={'on' if proxy_enabled else 'off'}"
    print(f"wrote functions/_middleware.js ({len(exact)} exact, {len(prefixes)} prefixes, {proxy_note})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
