#!/usr/bin/env python3
"""Step bank for MARKET_SUCCESS_1000 roadmap v3 — founder-only, unique steps every phase."""
from __future__ import annotations

# (name, archetype, tier, wins_one_liner, buyer, proof, gtm, signal_2026, copy, ignore, insight)
COMPANY_PROFILES: list[tuple[str, str, str, str, str, str, str, str, str, str, str]] = [
    (
        "Vanta",
        "A",
        "S0 · S4",
        "Continuous compliance → trust center → revenue unlock",
        "CISO / security (mid-market SaaS)",
        "Live trust center · SOC2/ISO badges · auto evidence collection",
        "Land SOC2 → expand frameworks → trust center self-serve",
        "16k+ customers · IDC/Forrester GRC leader · PLG + enterprise hybrid",
        "Self-serve diligence rail · honest Shipped grid · board PDF as unlock moment",
        "Full CCM platform · hundreds of integrations · SOC2 automation SKU",
        "Buyers pay to **stop losing deals** to security questionnaires — not for GRC theory.",
    ),
    (
        "Drata",
        "A",
        "S4 · S7",
        "Always audit-ready · continuous control monitoring rhythm",
        "CISO · engineering-led security orgs",
        "Real-time control status · auditor workspace · evidence freshness",
        "PLG + security community · MSP channel · framework expansion",
        "$100M+ ARR scale · multi-framework stickiness · always-on posture",
        "export_integrity fail-closed · live metadata index · continuous narrative copy",
        "Compete on framework count · generic compliance chat · payment rails",
        "Rhythm beats annual audit — **continuous proof** is the 2026 buyer expectation.",
    ),
    (
        "OneTrust",
        "C",
        "S4 · S2",
        "Unified trust platform · enterprise procurement umbrella",
        "CISO · privacy · legal (enterprise)",
        "Trust center · regulatory mapping · AI inventory under privacy brand",
        "Enterprise sales · land privacy → expand AI governance module",
        "14k+ orgs · broadest enterprise trust brand · privacy-first procurement",
        "Procurement pack under GRC budget · zone grid without vendor names",
        "Rip-and-replace Microsoft stack · become privacy platform",
        "Enterprise buys **one umbrella** — Noetfield is a slice: Copilot execution receipts.",
    ),
    (
        "Credo AI",
        "B",
        "S6 · S2",
        "Policy packs · governance-as-code evidence",
        "AI governance · GRC · legal (AI program owners)",
        "Policy pack activation · risk register · audit-ready evidence bundle",
        "Design partner → enterprise · IBM marketplace accelerators",
        "Gartner/Forrester cited · EU AI Act packs · IBM partnership 2026",
        "NIST AI RMF crosswalk on TLE · policy orientation rows · portable ZIP",
        "Full AI registry product · model lifecycle platform · chatbot SKU",
        "Regulation dates sell policy packs — **EU AI Act 2 Aug 2026** is your clock.",
    ),
    (
        "IBM watsonx.governance",
        "C",
        "S5 · S2",
        "Incumbent stack · FedRAMP lifecycle GRC for AI",
        "CRO · model risk · federal AI buyers",
        "AI factsheets · bias/drift monitoring · FedRAMP-oriented lifecycle",
        "IBM account attach · marketplace add-ons · services-led",
        "FedRAMP path · agent monitoring narrative 2026 · incumbent trust",
        "Complement watsonx/Copilot boundary doc · federal honest scope (not FedRAMP claim)",
        "Compete with IBM · build model training governance · claim FedRAMP",
        "Incumbents win on **procurement rail already approved** — attach, never rip.",
    ),
    (
        "ServiceNow AI Control Tower",
        "C",
        "S2",
        "Govern inside ITSM rail · no rip-and-replace",
        "CIO/CISO on ServiceNow platform",
        "Control tower dashboards · ITSM-linked risk · workflow-native AI governance",
        "Platform attach · expand module under existing SN contract",
        "Strong ServiceNow installed base · AI Control Tower 2025–2026 push",
        "RID handoff fields · Phase 2 after readiness · ITSM receipt complement",
        "Replace ServiceNow GRC · standalone ITSM · generic workflow builder",
        "Buyers with SN budget want **governance where tickets live** — export RID to their rail.",
    ),
    (
        "RegScale",
        "D",
        "S7 · S6",
        "Compliance-as-code · live control state",
        "CISO · federal · F500 GRC modernization",
        "Live control state · OSCAL exports · API-first evidence",
        "Federal + F500 · Series B May 2026 · compliance engineering buyers",
        "$30M+ Series B · 300% growth · 140% NRR · OSCAL-native posture",
        "TLE YAML machine-readable · OSCAL orientation · export_integrity timestamps",
        "Full GRC replacement · OSCAL platform SKU · federal ATO claims",
        "Compliance-as-code buyers want **API receipts**, not slide decks — TLE is your API artifact.",
    ),
    (
        "Complyance",
        "E",
        "S8",
        "Agentic GRC · workflow agents not chatbot SKU",
        "Enterprise GRC (healthcare · FS · tech)",
        "16+ GRC agents · 100+ frameworks · chore automation",
        "Stealth → GV Series A Feb 2026 · F500 design wins",
        "$28M raised · 70% manual GRC reduction claim · agent-per-workflow",
        "Internal triage/demo/verify agents only · never public agent SKU",
        "Public chatbot GRC · sell agents as product · TPRM platform",
        "Agents win on **specific chores** (evidence gather, questionnaire fill) — internal ops only.",
    ),
    (
        "MetricStream",
        "B+D",
        "S5 · S0",
        "Enterprise board reporting · regulated depth",
        "Global banks · insurers · energy CRO/GRC",
        "Enterprise risk register · exec dashboards · board reporting packs",
        "Long enterprise cycles · analyst-led Leader positioning",
        "IDC MarketScape Leader 2026 · regulated vertical depth",
        "Board PDF moment · Bank Pilot shadow · micro risk record per TLE",
        "Compete on GRC breadth · insurance vertical marketing · analyst stat claims on www",
        "Regulated buyers pay for **board-ready narrative** — one PDF in the meeting beats ten features.",
    ),
    (
        "Modulos",
        "B",
        "S6",
        "Governance Graph · framework dedup math",
        "GRC · AI program (EU/multinational)",
        "Cross-framework deduplication · overlap ROI · unified control mapping",
        "Hybrid PLG + enterprise · framework overlap ROI calculator",
        "Dedicated AIGP vs incumbents · EU AI Act crosswalk emphasis",
        "One TLE → many framework citations · internal dedup note only",
        "Governance Graph product fiction · compete on framework count",
        "Framework sprawl is the enemy — **one receipt, many citations** is Noetfield math.",
    ),
]

COMPANIES = [(p[0], p[1], p[2], p[3]) for p in COMPANY_PROFILES]

PHASE_I_VERBS = [
    "Capture success model — what buyer pays for vs what they ignore",
    "Extract proof artifact — the forwardable moment that closes diligence",
    "Map GTM motion to Noetfield three-SKU ladder (Trust Brief · Copilot · Bank Pilot)",
    "Assign Noetfield tier (S0–S8) — explicit copy vs ignore list",
    "List scope we must NOT build — anti-pattern guard for agents",
    "Identify primary buyer persona and first email persona line",
    "Note 2026 market signal — timing hook for outreach (no battlecard)",
    "Write internal playbook paragraph — ops/private sprint log only",
    "Define Noetfield golden adaptation — one sentence wedge from this model",
    "Close sprint: confirm zero vendor reference on public www + W3 relevance",
]


def company_analysis_steps() -> list[tuple[str, str, str, str]]:
    """Phase I: 10 companies × 10 analysis steps = 100 unique rows."""
    rows: list[tuple[str, str, str, str]] = []
    for profile in COMPANY_PROFILES:
        name, arch, tier, wins, _buyer, _proof, _gtm, signal, copy, ignore, insight = profile
        extras = [wins, copy, ignore, insight, signal]
        for i, verb in enumerate(PHASE_I_VERBS):
            detail = extras[i % len(extras)]
            rows.append(
                (
                    f"**{name}:** {verb} — {detail}",
                    f"Archetype {arch}",
                    tier,
                    f"{name} pattern locked internal · www clean",
                )
            )
    return rows


def _sprint_block(
    phase_arch: str,
    tier: str,
    sprint_name: str,
    tasks: list[str],
) -> list[tuple[str, str, str, str]]:
    out: list[tuple[str, str, str, str]] = []
    for i, task in enumerate(tasks):
        prefix = f"**{sprint_name}**" if i == 0 else sprint_name
        done = "Shipped artifact + verify green" if i == 9 else "Evidence in repo or export path"
        out.append((f"{prefix}: {task}", phase_arch, tier, done))
    return out


def _phase_from_sprints(
    arch: str,
    tier: str,
    sprints: list[tuple[str, list[str]]],
) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for name, tasks in sprints:
        if len(tasks) != 10:
            raise ValueError(f"Sprint {name!r} must have 10 tasks, got {len(tasks)}")
        rows.extend(_sprint_block(arch, tier, name, tasks))
    return rows


def phase_ii_steps() -> list[tuple[str, str, str, str]]:
    """Archetype A — Vanta · Drata: trust unlock."""
    return _phase_from_sprints(
        "A — Trust unlock",
        "S0 · S4",
        [
            ("Trust center IA (Vanta pattern)", [
                "Wire procurement rail: Trust · Pack · Samples · Verify on homepage",
                "Link footer Proof column to /trust/ /trust-ledger/verify/ samples",
                "Add trust diligence light theme body class on /trust/",
                "Honest cert table: Shipped · Orientation · Roadmap · N/A only",
                "Metadata-only M365 section with fail-closed export callout",
                "Cross-link procurement pack → trust center bidirectionally",
                "Print stylesheet on trust + procurement pages",
                "E2E grep: fail closed · Metadata-only on /trust/",
                "Regenerate www via rebuild-www-v6.py — no hand patches",
                "make verify-www PASS",
            ]),
            ("Board PDF moment — S0 wedge (MetricStream + Vanta)", [
                "Workspace: Board pack (PDF) export button on TLE detail",
                "Sample board PDF linked from /trust-ledger/sample-report/",
                "Demo script step 5: board governance meeting narrative",
                "Investor milestone row: first referenceable board PDF target",
                "Design partner SOW cites board PDF as named deliverable",
                "pytest test_tle_flow: export path includes PDF",
                "procurement-pack-e2e asserts PDF inside ZIP",
                "Honest scope grid marks board PDF Shipped today",
                "Remove dashboard-only proof from copilot hero copy",
                "W3 check: board PDF demoable in ≤5 minutes",
            ]),
            ("Questionnaire deflection (Drata continuous)", [
                "Procurement pack answers: metadata-only · three SKUs · no custody",
                "FAQ reframed: what Noetfield receipts — not comparison questions",
                "NIST AI RMF orientation block in procurement hub",
                "Sample TLE trio: go · conditional · rejected YAML downloadable",
                "Verify page tamper fail-closed walkthrough with CLI orientation",
                "Status page linked from trust footer diligence path",
                "Canada trust notes in COMMERCIAL_CLIENT_VC diligence doc",
                "Self-serve diligence path documented for procurement persona",
                "curl E2E: /copilot/procurement/ cross-links /trust/",
                "Procurement persona completes diligence without sales call",
            ]),
            ("Framework zone grid — S4 (OneTrust umbrella slice)", [
                "Zone grid: compliance automation · AI estate · decision evidence · MSP · Copilot receipts",
                "No vendor names in zone labels — buyer-safe pattern names only",
                "Investor page reuses same zone grid for consistency",
                "Homepage §08 What you get — execution receipts copy",
                "Category note: complement CCS — receipt operational go/no-go",
                "grep guard: no comparison framing on public html",
                "DESIGN_REFERENCE R1–R20 alignment review",
                "Federal hub framework marquee without certifier fiction",
                "Enterprise hub shows three SKU cards only",
                "verify-static-www investors honesty row PASS",
            ]),
            ("Land-expand motion (Vanta SOC2 → expand)", [
                "Trust Brief $10k land SKU copy locked in OFFERINGS_LOCKED",
                "Copilot Pack $2k–10k expand SKU on /copilot/pilot/",
                "Bank Pilot custom shadow lane documented honestly",
                "No fourth offering card anywhere on www",
                "Intake RID threading on gate/intake forms",
                "Design partner scarcity copy on homepage hero",
                "Investor land → expand → channel section complete",
                "GTM 60-day hook: signed TLE export for audit trail",
                "Outreach template in DESIGN_PARTNER_PIPELINE only",
                "Commercial SSOT tier alignment review signed off",
            ]),
            ("Live evidence posture (Drata always-on)", [
                "export_integrity fail-closed on every sample TLE YAML",
                "M365 evidence index fields populated on all samples",
                "confidence_score visible in demo step 4 script",
                "TLE refresh on policy change — Roadmap badge honest",
                "Continuous narrative in trust center copy (not fake hourly CCM)",
                "No fake SOC2 automation claims on public www",
                "Governance evaluate API returns signed decision + tenant_id",
                "Audit events pytest suite green",
                "tle-smoke.sh PASS on CI path",
                "M365 metadata stub seed script documented in ops",
            ]),
            ("Community PLG (Drata security community)", [
                "5-minute demo script locked in /copilot/demo/",
                "Demo rehearsal checklist updated in docs/copilot/",
                "Workspace demo link present in client chunk E2E",
                "print-demo-url.sh for founder tunnel shares",
                "No self-serve card checkout on institutional pages",
                "Request Governance Brief primary CTA on all hubs",
                "Receipt-first blog outline in ops/private only",
                "LinkedIn wedge: Copilot execution receipts — no vendor names",
                "Vancouver Trust Brief wedge in GTM lock doc",
                "First CIO contact metric row in tier1-status.json",
            ]),
            ("Auditor-friendly exports (RegScale + Vanta)", [
                "TLE v1 schema documented in spec/ with field glossary",
                "Three sample YAML: go · conditional · rejected",
                "Verify integrity walkthrough on /trust-ledger/verify/",
                "Board PDF + procurement ZIP bundle naming convention locked",
                "RID + tle_id on every export artifact",
                "PARTNER_PRE_EXECUTION ITSM handoff fields documented",
                "OpenAPI governance evaluate synced with shipped API",
                "validate-tle-schemas.sh PASS",
                "Diligence EVIDENCE_INTAKE_CONTRACT cross-linked",
                "Auditor replays verify without account — orientation only",
            ]),
            ("Multi-framework spine (Modulos dedup · Credo packs)", [
                "One TLE maps to NIST · AIA · ISO-style orientation rows",
                "AIA ↔ TLE mapping doc v1 current for federal lane",
                "Federal AIA preview table on /federal/ hub",
                "EU AI Act orientation row — not approver claim",
                "Framework citations included in procurement ZIP README",
                "No Governance Graph product fiction on www",
                "Crosswalk supplementary evidence disclaimer in pack",
                "Modulos dedup idea captured as internal note only",
                "Policy map listed in Trust Brief deliverable spec",
                "Framework grid passes verify-no-comparison guard",
            ]),
            ("Phase II closeout — trust unlock shipped", [
                "Run make verify-www full suite",
                "Run verify-ui-e2e on /trust/ /investors/ /",
                "Run make verify-market-roadmap",
                "Update tier1-status L-03 L-04 if milestones hit",
                "Capture screenshot paths in reports/ (gitignored ok)",
                "Founder review: trust center buyer-ready for diligence",
                "No vendor names grep on all public html",
                "Procurement rail present on all primary hubs",
                "S0 + S4 tiers marked implemented in roadmap index",
                "Phase II sign-off logged in ops/private sprint log",
            ]),
        ],
    )


def phase_iii_steps() -> list[tuple[str, str, str, str]]:
    """Archetype B — Credo AI · Modulos: AI policy product."""
    return _phase_from_sprints(
        "B — AI policy",
        "S6 · S2",
        [
            ("NIST AI RMF crosswalk on TLE (Credo pattern)", [
                "Map GOVERN · MAP · MEASURE · MANAGE to TLE body fields",
                "Add NIST AI RMF orientation row on procurement hub",
                "Sample TLE includes rmf_function tag in YAML",
                "Document crosswalk in GOVERNANCE_SOURCES_BOOK Part C",
                "Federal hub links NIST crosswalk without certifier claim",
                "pytest: sample YAML validates rmf fields",
                "Investor page cites NIST orientation — not compliance claim",
                "Remove any NIST 'certified' language grep",
                "Design partner workshop deck outline in ops/private",
                "verify-static-www copilot dual artifact PASS",
            ]),
            ("ISO 42001 orientation (Credo policy packs)", [
                "ISO 42001 orientation row in honest scope grid",
                "Trust Brief deliverable lists ISO-style evidence map",
                "Procurement ZIP README cites ISO orientation disclaimer",
                "Sources Book ISO 42001 section cross-linked from /trust/",
                "No ISO certification badge on www",
                "Sample TLE metadata field iso42001_control_ref optional",
                "FAQ: ISO alignment vs certification honest answer",
                "GRC persona copy on /copilot/sme/ mentions ISO orientation",
                "Internal policy pack template in ops/private",
                "grep: no ISO certifier fiction on public html",
            ]),
            ("EU AI Act Aug 2026 clock (Credo · Modulos)", [
                "EU AI Act high-risk orientation row — deadline 2 Aug 2026",
                "Homepage marquee includes EU AI Act orientation tag",
                "Procurement pack section: EU clock for multinational buyers",
                "TLE body field eu_ai_act_annex_ref optional orientation",
                "Federal hub excludes EU claims — Canada-first",
                "Investor market context row cites Aug 2026 deadline",
                "Design partner intake asks multinational exposure Y/N",
                "Sources Book EU section current",
                "No 'EU compliant' or approver language on www",
                "Roadmap badge honest: EU pack Orientation not Shipped",
            ]),
            ("Policy pack activation model (Credo GTM)", [
                "Define Trust Brief policy map as 'activation' deliverable",
                "Copilot Pack SOW cites activated policy crosswalk",
                "Workspace shows policy_version on TLE detail",
                "Document policy pack ≠ software SKU in PRODUCT_TRUTH",
                "Internal Credo-style pack outline: NIST + AIA + Copilot",
                "Demo step: show policy_version in TLE receipt mock",
                "No self-serve policy pack download on www",
                "Gate intake captures existing policy doc Y/N",
                "Agent prompt: never sell policy pack without Trust Brief path",
                "Commercial SSOT § policy deliverable alignment",
            ]),
            ("Governance Graph dedup math (Modulos internal)", [
                "Write internal note: one control → many framework citations",
                "TLE evidence_index supports multi-source without duplication",
                "Sample TLE shows purview · entra · audit single index",
                "No 'Governance Graph' product name on www",
                "Procurement copy: supplementary evidence disclaimer",
                "Calculate overlap ROI narrative for investor private brief",
                "Modulos pattern: dedup saves buyer questionnaire time",
                "Crosswalk table in ops/private only",
                "verify-no-comparison: no graph product claims",
                "Phase III checkpoint: policy orientation rows live",
            ]),
            ("Portable procurement ZIP (Credo export)", [
                "Procurement ZIP includes PDF + JSON + README + samples",
                "README lists frameworks cited and honest scope",
                "ZIP naming: noetfield-procurement-{tle_id}-{date}.zip",
                "procurement-pack-e2e validates README presence",
                "OpenAPI export endpoint documented",
                "Sample download from /trust-ledger/sample-report/",
                "Noetfield wedge: portable bundle none of ten sell pre-execution",
                "Partner handoff: ZIP acceptable in MS Teams diligence",
                "Audit export JSON separate from procurement ZIP",
                "make verify-gtm procurement-pack-e2e PASS",
            ]),
            ("confidence_score + approver_chain audit (Credo risk register)", [
                "confidence_score on every sample TLE YAML",
                "approver_chain array on signed TLE samples",
                "Result page shows Confidence score badge E2E",
                "TLE detail workspace shows confidence + approvers",
                "Demo script step 4 highlights confidence for board",
                "Audit events log confidence_factors from evaluate API",
                "Risk register alignment doc in ops/private",
                "No auto-approve without human sign-off copy",
                "pytest test_tle_flow confidence path green",
                "verify-ui-e2e result page confidence badge PASS",
            ]),
            ("IBM marketplace complement narrative (internal Credo channel)", [
                "Internal doc: Credo sells via IBM — Noetfield complements Copilot",
                "No IBM partnership claim on www",
                "Copilot hub copy: complement Purview + CCS",
                "Design partner ask: existing IBM/watsonx Y/N on intake",
                "Federal lane: watsonx boundary one paragraph internal",
                "Never 'integrated with IBM' on public surfaces",
                "Channel map in ops/private founder only",
                "GTM: sell to Copilot buyers not watsonx replacement",
                "grep: no IBM co-sell claims on www",
                "Archetype C handoff prep for Phase IV",
            ]),
            ("Workspace policy crosswalk demo (Credo buyer moment)", [
                "Workspace TLE detail shows framework_citations array",
                "Demo rehearsal adds crosswalk walkthrough step",
                "5-minute demo links to live workspace sample TLE",
                "SME pack page cites crosswalk in deliverable list",
                "Video script outline ops/private only",
                "E2E: workspace sample TLE loads citations",
                "No live policy engine — orientation badges only",
                "Trust center links workspace demo path",
                "Design partner success = crosswalk in board pack",
                "W3: crosswalk visible in forwarded PDF",
            ]),
            ("Phase III closeout — AI policy orientation shipped", [
                "All framework orientation rows on honest scope grid",
                "make verify-www + verify-ui-e2e green",
                "No vendor names on /copilot/ /federal/ /trust/",
                "Policy pack deliverable locked in OFFERINGS",
                "EU + NIST + ISO rows Orientation not Shipped",
                "Internal Modulos dedup note filed ops/private",
                "Founder review: policy story buyer-safe",
                "Update tier1-status S6 policy milestones",
                "Phase III sign-off sprint log",
                "Handoff brief for Phase IV incumbent attach",
            ]),
        ],
    )


def phase_iv_steps() -> list[tuple[str, str, str, str]]:
    """Archetype C — IBM watsonx · ServiceNow · OneTrust."""
    return _phase_from_sprints(
        "C — Incumbent attach",
        "S2",
        [
            ("Microsoft CCS stack ladder (Learn.microsoft.com)", [
                "Document CCS phases: readiness → control → receipt (internal)",
                "Copilot hub hero: Phase 2 after readiness copy",
                "MSP page: Phase 1 Purview · Phase 2 TLE attach",
                "No 'replace CCS' language anywhere grep",
                "Link Learn.microsoft.com Copilot governance docs orientation",
                "Demo narrative: show receipt after Microsoft readiness",
                "Federal hub: Copilot PIN + readiness sequence",
                "PRODUCT_TRUTH complement stack section current",
                "verify-static-www no comparison framing PASS",
                "Design partner FAQ: where Noetfield sits in CCS ladder",
            ]),
            ("Purview metadata-only connectors (IBM · Microsoft stack)", [
                "M365 connectors page: metadata-only callout prominent",
                "Evidence stub seed: Purview · Entra · audit labels",
                "TLE samples show evidence_index without content custody",
                "Trust center: no content download · index only",
                "Connector OAuth mock E2E green",
                "PARTNER doc: what metadata fields indexed",
                "No DLP replacement claims on www",
                "pytest connector ingest path green",
                "Demo step 3: evidence index from connectors",
                "grep: no 'replace Purview' on public html",
            ]),
            ("Phase 2 after readiness copy (ServiceNow attach pattern)", [
                "Rewrite MSP hero: Readiness → Record · Phase 2 TLE",
                "Copilot pilot SOW template Phase 2 language",
                "Homepage loop: Evaluate after readiness implied",
                "No Phase 1 compete — partner enables Phase 1",
                "Internal ServiceNow: govern where tickets live note",
                "RID export for ITSM paste fields documented",
                "Bank Pilot: shadow after readiness only",
                "GTM 60-day: never sell before Purview baseline",
                "verify-ui-e2e MSP lane Readiness → Record PASS",
                "Founder talk track: attach not rip-and-replace",
            ]),
            ("ServiceNow RID handoff doc (Control Tower pattern)", [
                "Document RID + decision + confidence for SN paste",
                "OpenAPI evaluate response fields for ITSM integration",
                "ops/private ITSM handoff one-pager",
                "No ServiceNow partnership logo on www",
                "Procurement pack ITSM section orientation",
                "Design partner: ServiceNow shop Y/N intake",
                "Export JSON schema includes rid tenant_id decision",
                "Never 'ServiceNow module' product claim",
                "Agent rule: SN buyers get complement copy only",
                "Phase IV checkpoint: handoff doc complete",
            ]),
            ("OneTrust umbrella slice positioning (internal)", [
                "Internal: Noetfield = Copilot receipt slice under GRC budget",
                "Procurement copy: fits existing GRC line item",
                "Zone grid: decision evidence zone for Noetfield",
                "No OneTrust comparison on www ever",
                "Enterprise hub: three SKUs under enterprise GRC buyer",
                "Trust Brief opens umbrella diligence path",
                "Investor: slice not platform TAM story",
                "grep OneTrust name excluded from public html",
                "Commercial SSOT attach positioning review",
                "Founder: sell to Copilot owner not privacy suite owner first",
            ]),
            ("watsonx vs Copilot receipt boundary (IBM)", [
                "Internal boundary doc: watsonx governs models · Noetfield Copilot ops",
                "Federal lane honest: not FedRAMP · not IBM partner claim",
                "Bank Pilot: model risk shadow separate from TLE",
                "No watsonx logo or integration claim www",
                "Design partner: watsonx deployment Y/N",
                "Sources Book IBM section orientation only",
                "CRO persona copy on enterprise hub restrained",
                "grep watsonx excluded public surfaces",
                "Agent handoff: federal IBM shops get Bank Pilot path",
                "Never compete with IBM account team",
            ]),
            ("Control tower workspace mock (ServiceNow UX pattern)", [
                "Cognitive dashboard: operational intent submit UX polished",
                "Evaluate → result → workspace path E2E green",
                "Audit log page linked from result",
                "Dashboard copy: pre-execution governance not ITSM",
                "No 'control tower' product name on www",
                "Demo shows dashboard as evaluate entry point",
                "Shell nav: workspace · evaluate · audit consistent",
                "verify-ui-e2e cognitive dashboard PASS",
                "Mobile-readable evaluate form smoke",
                "Founder demo uses dashboard not raw API",
            ]),
            ("Federal honest scope — not FedRAMP (watsonx lesson)", [
                "/federal/ hub: not a federal certifier disclaimer",
                "GC ADM · AIA · Copilot PIN docs linked",
                "June 24 2026 ADS deadline callout on federal hub",
                "No FedRAMP badge or authorization claim",
                "Trust Brief federal attach path documented",
                "canada.ca + tbs-sct links only — primary sources",
                "grep FedRAMP on www returns orientation disclaimer only",
                "Design partner federal: department schedule intake",
                "Bank Pilot for FRFI separate from GC hub",
                "verify-ui-e2e federal lane PASS",
            ]),
            ("Module expand Copilot → Trust Brief (OneTrust land-expand)", [
                "Copilot pilot success criteria → Trust Brief upsell path",
                "SOW template expansion clause after 90 days",
                "Investor land-expand table includes Trust Brief",
                "No fourth SKU — expansion is services depth",
                "GTM: design partner → Trust Brief → annual governance",
                "Pricing honest: no fake MRR product on www",
                "Governance Monitor MRR Roadmap badge only",
                "Commercial SSOT expansion motion locked",
                "Founder CRM: track expand signal per partner",
                "W3 expand: Trust Brief deposit after pilot",
            ]),
            ("Phase IV closeout — incumbent attach copy verified", [
                "grep complement not replace on all copilot pages",
                "No IBM · ServiceNow · OneTrust names on www",
                "RID handoff doc in ops/private complete",
                "MSP Phase 2 copy live on /msp/",
                "make verify-www + verify-gtm green",
                "Federal honest scope review signed",
                "Founder talk track recorded ops/private",
                "tier1-status S2 attach milestones updated",
                "Phase IV sign-off sprint log",
                "Handoff brief Phase V continuous assurance",
            ]),
        ],
    )


def phase_v_steps() -> list[tuple[str, str, str, str]]:
    """Archetype D — RegScale: continuous assurance."""
    return _phase_from_sprints(
        "D — Continuous assurance",
        "S7 · S6",
        [
            ("TLE YAML machine-readable receipt (RegScale API pattern)", [
                "TLE v1 YAML schema version field locked",
                "All samples validate against schema script",
                "Download YAML from sample-report hub",
                "API GET /tle/{id} returns same shape as YAML export",
                "OpenAPI documents TLE response schema",
                "Machine-readable emphasized in procurement README",
                "Noetfield gap: pre-execution receipt none of ten match",
                "Developer doc orientation at /docs/api/",
                "pytest schema validation green",
                "verify-local-dev TLE sample YAML download PASS",
            ]),
            ("OSCAL orientation doc (RegScale native)", [
                "Write ops/private OSCAL ↔ TLE field mapping orientation",
                "No OSCAL export product claim on www",
                "RegScale pattern: compliance-as-code buyers want OSCAL",
                "TLE as simpler wedge before OSCAL maturity",
                "Federal buyer brief mentions OSCAL orientation",
                "Sources Book OSCAL paragraph orientation",
                "Roadmap badge: OSCAL export Orientation",
                "Never 'OSCAL certified' language",
                "Partner doc: TLE now · OSCAL later internal",
                "grep OSCAL returns orientation only on www",
            ]),
            ("export_integrity timestamps (continuous proof)", [
                "Every sample TLE includes signed_at timestamp",
                "Verify page explains fail-closed on tamper",
                "export_integrity: fail closed in all sample YAML",
                "Audit export includes integrity hash orientation",
                "Demo: tamper walkthrough on verify page",
                "Drata-style continuous copy on trust center",
                "No fake real-time SOC2 monitoring claims",
                "pytest export integrity path green",
                "tle-smoke validates integrity fields",
                "verify-ui-e2e tle verify fail closed PASS",
            ]),
            ("Measure time-to-first-TLE (RegScale velocity metric)", [
                "Define internal KPI: minutes from evaluate to signed TLE",
                "copilot-pilot-e2e times logged in sprint log",
                "Demo script targets ≤15 min first TLE",
                "Design partner onboarding checklist timed",
                "Investor honest: early metric founder-measured",
                "No fake customer stat on www",
                "tier1-status time_to_first_tle row",
                "Workspace UX reduces clicks to sign TLE",
                "Founder tracks partner #1 TLE timestamp",
                "W3: first TLE in partner tenant ≤ pilot week 2",
            ]),
            ("Audit prep ZIP+PDF bundle (always audit-ready)", [
                "Single click procurement ZIP from signed TLE",
                "Board PDF inside partner workflow documented",
                "Audit prep checklist ops/private for founders",
                "Bundle contents listed in procurement pack",
                "procurement-pack-e2e full PASS",
                "Auditor replay without login orientation",
                "RegScale NRR lesson: expansion via depth not SKUs",
                "No 'audit guaranteed' language www",
                "GRC persona: always-ready narrative on /trust/",
                "make verify-gtm includes pack e2e",
            ]),
            ("OpenAPI evaluate partner doc (API-first GRC)", [
                "/docs/api/ hub current with evaluate endpoint",
                "POST /evaluate example curl on docs page",
                "Partner MSB openapi verify script green",
                "tenant_id in evaluate response documented",
                "RID threading documented for integrators",
                "No public API key self-serve — intake only",
                "RegScale buyer profile: API evidence consumers",
                "Internal: webhook export Roadmap badge",
                "pytest evaluate contract stable",
                "verify-local-dev governance evaluate PASS",
            ]),
            ("GC ADM federal CCM attach (RegScale federal)", [
                "Federal hub ADM directive link current",
                "AIA preview table aligned TLE fields",
                "June 2026 deadline prominent on /federal/",
                "Trust Brief federal SOW template ADM section",
                "No GC certifier claim",
                "GC buyer talk track ops/private",
                "Copilot PIN link from federal hub",
                "Design partner federal intake fields",
                "grep federal certifier fiction clean",
                "verify-ui-e2e federal lane PASS",
            ]),
            ("Expand seats not SKUs (RegScale NRR discipline)", [
                "Commercial SSOT: three SKUs forever rule",
                "Expansion = more TLE volume · more tenants · Trust Brief",
                "No fourth product card grep guard",
                "Investor: seat expansion via MSP multi-tenant",
                "MSP Phase 2 pricing $2k–10k per tenant",
                "No feature-gated SKU tiers on www",
                "Governance Monitor MRR stays Roadmap",
                "Founder CRM expansion tracked separately",
                "Drata lesson: frameworks expand · we expand receipts",
                "OFFERINGS_LOCKED review no SKU creep",
            ]),
            ("TLE refresh Roadmap badge (continuous vs point-in-time)", [
                "Honest scope: TLE refresh on policy change = Roadmap",
                "Trust center copy: point-in-time receipt today",
                "No fake continuous monitoring product claim",
                "Drata always-on narrative adapted honestly",
                "Design partner sets refresh expectations in SOW",
                "Internal RegScale CCM aspiration doc",
                "export_integrity today · refresh tomorrow honest",
                "Investor roadmap slide continuous receipt vision",
                "Agent rule: never claim hourly CCM",
                "Roadmap badge visible on homepage scope grid",
            ]),
            ("Phase V closeout — continuous receipt discipline", [
                "All integrity + YAML paths green",
                "make verify-gtm + tle-smoke PASS",
                "OSCAL orientation doc filed ops/private",
                "time-to-first-TLE metric defined",
                "API docs current at /docs/api/",
                "Federal ADM attach copy live",
                "No SKU creep verified",
                "tier1-status S7 milestones updated",
                "Phase V sign-off sprint log",
                "Handoff Phase VI agentic ops internal",
            ]),
        ],
    )


def phase_vi_steps() -> list[tuple[str, str, str, str]]:
    """Archetype E — Complyance: agentic GRC internal only."""
    return _phase_from_sprints(
        "E — Agentic GRC",
        "S8",
        [
            ("Intake triage agent (internal Complyance pattern)", [
                "Define agent scope: classify gate intake by SKU lane",
                "Agent runs local only — no cloud agent SKU",
                "Output: routed folder ops/private/intake/",
                "Human approves every external reply",
                "Never mention agent on www or outreach",
                "Log agent decisions in sprint log not buyer-facing",
                "Complyance lesson: agents per workflow chore",
                "Forbidden: public chatbot on noetfield.com",
                "Cursor rule: agentic ops internal only",
                "Verify agent-scope script PASS",
            ]),
            ("Demo rehearsal agent (internal)", [
                "Agent generates demo checklist from verify-gtm output",
                "Founder reviews before every external demo",
                "5-minute demo script version controlled",
                "Agent cannot send emails autonomously",
                "Record demo dry-run timestamps ops/private",
                "Complyance 70% reduction claim — internal ops only",
                "No 'AI demo coach' product marketing",
                "Human delivers all demos in W3 window",
                "Demo URL print script for tunnel shares",
                "copilot-pilot-e2e as demo gate before external",
            ]),
            ("Verify gate agent (internal quality)", [
                "Agent runs make verify-www before www commit suggest",
                "Agent blocked from skipping verify-no-competitor-names",
                "Fail-closed: agent cannot publish www without PASS",
                "verify-agent-scope documents allowed agent actions",
                "Human merges all www changes",
                "Agent logs verify output to ops/private/",
                "Never trust agent 'looks good' without script",
                "Complyance pattern: agent gathers · human decides",
                "CI path: verify-all-static on release branch",
                "Founder weekly verify-gtm ritual locked",
            ]),
            ("TPRM boundaries in pack only (Complyance scope)", [
                "TPRM mentioned orientation only in procurement pack",
                "No TPRM product SKU or hub page",
                "Trust Brief can mention vendor risk map deliverable",
                "No third-party vendor names in TPRM section",
                "Complyance sells broad GRC — we stay Copilot receipt",
                "grep TPRM on www returns pack mention only",
                "Agent forbidden from building /tprm/ route",
                "Commercial SSOT boundary review",
                "Design partner scope excludes TPRM platform",
                "Founder: defer TPRM until W3 with 3 partners",
            ]),
            ("Founder outreach time tracking (agentic ops ROI)", [
                "Track hours/week on outreach vs product verify",
                "Target: 50% product proof · 50% partner pipeline",
                "Agent drafts outreach — founder sends manually",
                "No automated LinkedIn DMs",
                "Vancouver ICP list ops/private only",
                "Complyance lesson: automate chores not relationships",
                "CRM minimal: design partner stage only",
                "W3 metric: deposits not emails sent",
                "Weekly founder log template ops/private",
                "Reject growth hacks that violate buyer-safe copy",
            ]),
            ("One design partner contract (focus discipline)", [
                "Single design partner deep engagement before second",
                "SOW template locked Copilot Governance Pack",
                "Deposit ≥ CAD 2K or signed LOI for W3",
                "90-day milestone board PDF in meeting",
                "No parallel pilot chaos — founder capacity honest",
                "Complyance F500 wins lesson: depth before breadth",
                "Partner success criteria documented",
                "Reference permission clause in SOW",
                "Track partner tenant time-to-first-TLE",
                "Founder review weekly partner status",
            ]),
            ("No agent SKU on www (hard guard)", [
                "grep agent SKU on public html must fail",
                "Homepage: governance execution not AI agents",
                "Copilot hub: receipts not bots",
                "ai-automation lane B: defensible automation copy only",
                "Forbidden: 'AI agent platform' anywhere public",
                "verify-no-competitor-names includes agent SKU patterns",
                "PRODUCT_TRUTH agent boundary section",
                "TrustField automation stays separate repo",
                "Cursor rule noetfield-no-vendor-names extended",
                "Founder sign-off agent guard quarterly",
            ]),
            ("5-min demo PLG (Complyance + Drata hybrid internal)", [
                "/copilot/demo/ hub buyer-ready",
                "Demo does not require login for narrative sections",
                "Live demo uses local dev stack verify-gtm path",
                "PLG = demo + intake not self-serve checkout",
                "Receipt-first PLG wedge copy locked",
                "No freemium TLE tier on www",
                "Community: security leaders not developer PLG",
                "Demo converts to Request Governance Brief",
                "verify-ui-e2e copilot demo PASS",
                "First external demo after verify-gtm green only",
            ]),
            ("Vancouver regulated SMB ICP (focused GTM)", [
                "Trust Brief wedge: healthcare OR legal/accounting",
                "GTM lock geo primary Vancouver 30-day",
                "Outreach templates Vancouver-specific ops/private",
                "No global ICP spray on www",
                "StatCan AI adoption stat orientation internal",
                "Design partner ICP scorecard",
                "Federal + MSP parallel but secondary",
                "Founder calendar: Vancouver meetings first",
                "W3 Vancouver Trust Brief deposit target",
                "ICP review monthly ops/private",
            ]),
            ("Phase VI closeout — agentic ops bounded", [
                "verify-agent-scope PASS",
                "No agent SKU on public www grep clean",
                "Internal agents documented ops/private only",
                "One design partner SOW ready to sign",
                "Demo PLG path green verify-ui-e2e",
                "Vancouver ICP outreach list current",
                "Founder time tracking template in use",
                "TPRM boundaries respected",
                "Phase VI sign-off sprint log",
                "Handoff Phase VII enterprise regulated",
            ]),
        ],
    )


def phase_vii_steps() -> list[tuple[str, str, str, str]]:
    """Enterprise regulated — MetricStream · IBM watsonx depth."""
    return _phase_from_sprints(
        "B+D Enterprise regulated",
        "S5 · S0",
        [
            ("Board PDF governance meeting (MetricStream pattern)", [
                "Board pack PDF template professional typography",
                "Sample PDF linked from investors private brief",
                "Demo step: 'put this PDF in governance meeting'",
                "Trust Brief deliverable includes exec summary PDF",
                "No fake Fortune 500 logo wall on www",
                "MetricStream lesson: exec narrative closes deals",
                "Board PDF includes confidence + decision + RID",
                "procurement-pack-e2e PDF assertion green",
                "Founder target: PDF forwarded by partner CISO",
                "W3: referenceable board PDF in real meeting",
            ]),
            ("GC ADM · Copilot PIN · AIA docs (watsonx federal)", [
                "Federal hub trilogy links: ADM · PIN · AIA",
                "AIA ↔ TLE mapping table on /federal/",
                "June 24 2026 ADS deadline banner",
                "Algorithmic Impact Assessment orientation copy",
                "Not a federal certifier disclaimer visible",
                "Trust Brief federal attach SOW section",
                "GC design partner intake department field",
                "Primary sources canada.ca tbs-sct only",
                "verify-ui-e2e federal lane complete PASS",
                "Founder federal talk track ops/private",
            ]),
            ("Bank Pilot shadow read-only (FRFI regulated)", [
                "Bank Pilot page honest: shadow · no execution authority",
                "No payment rails · no custody copy prominent",
                "Separate from Copilot Pack SKU on www",
                "SOW template read-only simulation clauses",
                "MetricStream banks lesson: long cycle · high trust",
                "FRFI intake separate gate form orientation",
                "No bank logo claims on www",
                "RPAA-safe vendor badge on homepage marquee",
                "Design partner bank: compliance intro only",
                "grep bank pilot honest scope PASS",
            ]),
            ("No analyst stats on www (MetricStream lesson)", [
                "Remove any Forrester/Gartner stat from public html",
                "Investor page: orientation not analyst badges",
                "grep Gartner Forrester IDC on www returns clean",
                "Internal analyst research ops/private only",
                "Honest scope moat over borrowed credibility",
                "Credo lesson: analyst cite internal not www",
                "verify-no-competitor-names extended patterns",
                "Founder: earn citations with partner references first",
                "Roadmap: analyst mention after 3 references",
                "verify-static-www investors honesty PASS",
            ]),
            ("TLE as micro risk record (MetricStream register)", [
                "Each TLE maps to single decision risk record",
                "TLE list API paginated for audit trail",
                "Audit log export JSON for compliance tools",
                "No enterprise GRC register product claim",
                "Micro record narrative on copilot hub",
                "Sample TLE shows risk_summary field",
                "evaluate API returns risk_score + factors",
                "pytest audit trail continuity green",
                "Workspace list shows decision history",
                "Buyer language: receipt not full GRC register",
            ]),
            ("Defer insurance vertical marketing (focus)", [
                "No insurance hub page on www",
                "Insurance mentioned only in enterprise orientation",
                "MetricStream vertical lesson: deep not wide",
                "Founder defers vertical pages until W3",
                "ICP stays Copilot governance cross-industry",
                "grep insurance product claims clean",
                "Bank Pilot covers FRFI without insurance SKU",
                "Commercial SSOT vertical discipline",
                "Agent forbidden from /insurance/ route",
                "Phase VII focus: board + federal + bank only",
            ]),
            ("Trust Brief opens CIO cycle (enterprise land)", [
                "Trust Brief $10k as enterprise door opener",
                "6-week deliverable list locked OFFERINGS",
                "Intake form captures CIO vs CISO sponsor",
                "Executive summary template ops/private",
                "Land before Copilot Pack pilot attachment",
                "Vancouver Trust Brief wedge primary",
                "No discount pricing on www",
                "Founder: Trust Brief funds product proof runway",
                "GTM 60-day Trust Brief outreach cadence",
                "W3: Trust Brief deposit closes land motion",
            ]),
            ("Minutes-to-export ROI honest (buyer math)", [
                "Document ROI: hours saved packaging audit evidence",
                "No fake 70% reduction stat on www (Complyance)",
                "Honest: founder-measured early partner data only",
                "Demo shows export in minutes not days",
                "Procurement pack ROI section restrained",
                "Investor private brief ROI model spreadsheet",
                "grep percentage claims on www audit clean",
                "Buyer debrief template captures time saved",
                "Partner interview ROI after pilot week 8",
                "W3 evidence: partner quote not invented stat",
            ]),
            ("Services cash now discipline (enterprise cycle)", [
                "Trust Brief delivers services cash in 6 weeks",
                "Copilot Pack pilot fee before heavy product build",
                "No free pilot without LOI or deposit",
                "MetricStream long cycle lesson: services bridge",
                "Founder runway tied to Trust Brief closes",
                "Bank Pilot custom scoping fee orientation",
                "No venture-scale burn on pre-W3 features",
                "Commercial SSOT services-first 2026",
                "Agent rule: no build without deposit signal",
                "Monthly founder cash pipeline review",
            ]),
            ("Phase VII closeout — enterprise lane honest", [
                "Board PDF · federal · bank paths verified",
                "No analyst stats on public www",
                "Trust Brief intake live and tested",
                "make verify-gtm full green",
                "Enterprise copy buyer-safe review",
                "tier1-status S5 milestones updated",
                "Insurance vertical deferred confirmed",
                "ROI claims honest audit PASS",
                "Phase VII sign-off sprint log",
                "Handoff Phase VIII MSP channel",
            ]),
        ],
    )


def phase_viii_steps() -> list[tuple[str, str, str, str]]:
    """Channel — MSP · Microsoft CSP attach."""
    return _phase_from_sprints(
        "A channel · MSP",
        "S3",
        [
            ("MSP Phase 1 RACI doc (partner enablement)", [
                "Write MSP Phase 1 RACI: partner owns Purview readiness",
                "Noetfield owns Phase 2 TLE attach only",
                "ops/private MSP_ENABLEMENT_v1.md",
                "RACI table: CSP · customer · Noetfield roles",
                "No MSP certifier or Microsoft partner claim www",
                "Partner intake form MSP Y/N on gate",
                "Phase 1 Noetfield does not compete with CSP",
                "READINESS_TO_RECORD mapping doc current",
                "Founder MSP talk track recorded",
                "grep MSP partner honest on /msp/ PASS",
            ]),
            ("Phase 2 TLE attach (Noetfield wedge)", [
                "/msp/ hero Readiness → Record live",
                "Phase 2 SOW template for MSP sub-contract",
                "MSP margin guidance $2k–10k internal ops",
                "Multi-tenant metadata-only architecture note",
                "TLE receipt after partner readiness sign-off",
                "Demo path for MSP partner enablement call",
                "W3-MSP: one live tenant Phase 2 TLE",
                "verify-ui-e2e msp partner lane PASS",
                "No white-label Noetfield SKU for MSP yet",
                "Partner pack PDF orientation ops/private",
            ]),
            ("Readiness → Record hero (buyer + partner)", [
                "MSP page narrative matches homepage specialized lanes",
                "Copilot hub links MSP partner path",
                "Federal hub excludes MSP confusion",
                "Phase 1 · Phase 2 visual on /msp/",
                "Partner CTA: Request Governance Brief MSP lane",
                "No MSP self-serve portal on www",
                "Founder outreach: 5 MSP targets Vancouver",
                "CSP 3-year Copilot attach note internal",
                "June 2026 Elevate Copilot SOW window doc",
                "grep Readiness → Record on /msp/ PASS",
            ]),
            ("W3-MSP LOI + 1 tenant (channel proof)", [
                "MSP LOI template ops/private",
                "Target: 1 MSP signed LOI parallel design partner",
                "LOI cites Phase 2 TLE attach scope",
                "One live tenant TLE in MSP customer env",
                "Multi-tenant tenant_id isolation verified pytest",
                "MSP partner not required for first W3",
                "Channel proof supplements direct W3",
                "Founder tracks MSP pipeline separately",
                "Deposit or LOI before MSP enablement call",
                "W3-MSP logged in tier1-status.json",
            ]),
            ("CSP 3-year Copilot attach note (Microsoft 2026)", [
                "Internal note: May 2026 CSP 3-year Copilot SKUs",
                "MSP margin on governance attach not Copilot resale",
                "No Microsoft partnership claim www",
                "Partner Center link orientation ops/private",
                "Purview Suite promo Jun 30 2026 deadline note",
                "MSP talk track: attach governance to Copilot deal",
                "Noetfield does not resell Copilot licenses",
                "Founder targets MSPs with Copilot pipeline",
                "READINESS_TO_RECORD ties to Purview promo window",
                "grep Microsoft partner fiction clean",
            ]),
            ("Elevate Copilot SOW window Jun 2026 (timing)", [
                "Internal calendar: Elevate Copilot SOW deadline",
                "MSP outreach before June 2026 window closes",
                "Talk track: Phase 2 receipt before SOW signature",
                "No deadline fear marketing on www",
                "Founder priority MSP meetings Q2 2026",
                "Ops/private MSP_TARGET_LIST_v1.md",
                "Partner demo before LOI",
                "W3-MSP can use Jun window as urgency internal",
                "Post-window: Trust Brief land for MSPs missed",
                "Sprint log tracks MSP window actions",
            ]),
            ("SPARK propensity founder targets (MSP GTM)", [
                "Define SPARK: MSPs with Copilot propensity score",
                "Internal list 10 MSP targets BC region",
                "Outreach sequence ops/private not automated send",
                "No SPARK trademark on www",
                "Partner fit scorecard: readiness capacity · Copilot pipeline",
                "Founder manual outreach only",
                "First MSP meeting notes template",
                "Reject MSPs wanting white-label engine SKU",
                "Commercial SSOT MSP ICP aligned",
                "Weekly MSP pipeline review 15 min",
            ]),
            ("Multi-tenant metadata-only (MSP technical)", [
                "tenant_id on evaluate · ingest · TLE API",
                "pytest tenant isolation paths green",
                "No cross-tenant evidence leak test",
                "Metadata-only per tenant documented",
                "MSP technical FAQ ops/private",
                "No content custody per tenant guarantee copy",
                "Connector OAuth per tenant workspace",
                "verify-local-dev tenant_id evaluate PASS",
                "Architecture note ops/private MSP multi-tenant",
                "Security review before MSP prod tenant",
            ]),
            ("Phase 2 margin $2k–10k (MSP economics)", [
                "Copilot Pack pricing band on /copilot/pilot/",
                "MSP sub-contract pricing guidance internal",
                "Margin enough for partner + Noetfield delivery",
                "No race-to-bottom pricing on www",
                "Trust Brief $10k separate from MSP Phase 2",
                "Founder models MSP deal economics spreadsheet",
                "W3-MSP revenue share orientation doc",
                "Three SKUs unchanged for MSP attach",
                "Bank Pilot not sold through MSP channel yet",
                "Commercial SSOT pricing review MSP section",
            ]),
            ("Phase VIII closeout — MSP channel ready", [
                "/msp/ hub buyer + partner ready",
                "RACI + READINESS_TO_RECORD docs complete",
                "verify-ui-e2e msp lane green",
                "LOI template ready to send",
                "10 MSP targets listed internal",
                "Multi-tenant tests green",
                "CSP timing note calendar set",
                "tier1-status S3 MSP milestones",
                "Phase VIII sign-off sprint log",
                "Handoff Phase IX product wedge",
            ]),
        ],
    )


def phase_ix_product_steps() -> list[tuple[str, str, str, str]]:
    """Noetfield receipt wedge — product proof (synthesis of all ten models)."""
    return _phase_from_sprints(
        "Receipt layer · Noetfield only",
        "S0 · S6",
        [
            ("Pre-execution evaluate API (unique wedge)", [
                "POST /evaluate returns decision risk_score rid tenant_id",
                "Evaluate page UX: Submit operational intent",
                "Cognitive dashboard evaluate entry E2E",
                "No competitor productizes pre-Copilot receipt",
                "OpenAPI spec synced with shipped fields",
                "pytest evaluate contract regression green",
                "Demo step 1: evaluate live",
                "Shadow mode documented for Bank Pilot",
                "verify-local-dev evaluate via proxy PASS",
                "Golden rule: evaluate before operational act",
            ]),
            ("Signed TLE v1 fields shipped (product core)", [
                "tle_id decision confidence_score approver_chain signed_at",
                "TLE draft → approve → sign lifecycle pytest green",
                "Workspace create TLE draft UX E2E",
                "Sample TLE trio on sample-report hub",
                "TLE list API paginated",
                "Schema validate-tle-schemas.sh PASS",
                "Noetfield product truth aligned PRODUCT_TRUTH.md",
                "Export only after sign — fail closed",
                "verify-ui-e2e workspace list PASS",
                "All ten models lack this exact artifact — moat",
            ]),
            ("Fail-closed tamper verify page (Drata · RegScale)", [
                "/trust-ledger/verify/ hub buyer-ready",
                "Walkthrough: alter YAML → verify fails",
                "export_integrity field on all samples",
                "CLI verify orientation in docs",
                "Demo step: tamper fail closed narrative",
                "Trust center links verify path",
                "procurement pack mentions verify",
                "pytest integrity tamper case green",
                "verify-ui-e2e tle verify PASS",
                "Auditor-friendly replay without account",
            ]),
            ("Board PDF export E2E (Vanta · MetricStream)", [
                "Board pack PDF button on TLE detail",
                "copilot-pilot-e2e step 5 PDF export",
                "Sample PDF downloadable",
                "PDF includes decision confidence RID",
                "Professional layout smoke test",
                "Demo board meeting script references PDF",
                "Trust Brief cites board PDF deliverable",
                "No PDF without signed TLE — fail closed",
                "procurement-pack-e2e PDF in ZIP",
                "W3 gate: PDF in real governance meeting",
            ]),
            ("Procurement ZIP export E2E (OneTrust · Credo)", [
                "Procurement pack ZIP from signed TLE",
                "ZIP: PDF + JSON + README + sample YAML",
                "procurement-pack-e2e full lifecycle PASS",
                "Naming convention locked",
                "Procurement hub links live export demo",
                "Buyer diligence without sales call",
                "NIST AI RMF citations in README orientation",
                "verify-gtm includes procurement e2e",
                "Partner can forward ZIP in Teams",
                "Golden rule: proof before pitch",
            ]),
            ("M365 evidence index stub (Microsoft stack)", [
                "Purview · Entra · audit evidence labels on TLE",
                "Connector OAuth mock flow E2E green",
                "seed-m365-evidence-stub.sh documented",
                "Metadata-only — no content custody",
                "Demo step 3: evidence index visible",
                "Trust center metadata-only section",
                "Complement Purview copy verified",
                "pytest evidence ingest green",
                "FRFI-safe posture documented",
                "grep replace Purview clean",
            ]),
            ("5-minute demo all steps (PLG receipt)", [
                "/copilot/demo/ script covers evaluate → TLE → export",
                "Demo runnable after verify-gtm green",
                "All 5 steps under 5 minutes timed",
                "Confidence score shown step 4",
                "Verify tamper step optional 6",
                "Demo links workspace + samples",
                "No login required for static demo sections",
                "verify-ui-e2e copilot demo PASS",
                "Founder rehearsal before external demo",
                "Receipt-first PLG converts to intake",
            ]),
            ("Workspace evaluate→export UX (product loop)", [
                "Path: evaluate → result → workspace → TLE → export",
                "verify-ui-e2e full loop green",
                "Shell nav consistent across product pages",
                "OAuth success banner E2E",
                "Connectors not captured by [tle_id] route",
                "Mobile smoke evaluate form",
                "Error states human-readable",
                "Loading states on result page",
                "RidCopy component on result",
                "Product loop demoable ≤15 min first TLE",
            ]),
            ("Design partner 90-day SOW (GTM product fit)", [
                "SOW template locked 90-day design partner",
                "Milestones: week 2 first TLE · week 8 board PDF",
                "Success criteria measurable",
                "Deposit ≥ CAD 2K clause",
                "Reference permission clause",
                "Scope excludes engine SKU · payment rails",
                "Three SKU alignment Copilot Pack",
                "Founder signs before build scope creep",
                "Partner onboarding checklist",
                "W3 economic signal defined in SOW",
            ]),
            ("Phase IX closeout — product wedge proven", [
                "make verify-gtm full green from scratch",
                "make verify-ui-e2e all product checks PASS",
                "copilot-pilot-e2e + procurement-pack-e2e PASS",
                "21 pytest backend green",
                "No vendor names public www",
                "All sample artifacts current",
                "Demo script matches shipped product",
                "tier1-status product milestones complete",
                "Phase IX sign-off sprint log",
                "Handoff Phase X W3 scale capital",
            ]),
        ],
    )


def phase_x_steps() -> list[tuple[str, str, str, str]]:
    """W3 proof · scale · capital readiness — synthesis closeout."""
    return _phase_from_sprints(
        "All archetypes · W3 closeout",
        "S0–S8",
        [
            ("First design partner deposit ≥ CAD 2K (W3 economic)", [
                "Close first design partner deposit or signed LOI",
                "Log deposit date ops/private W3 log",
                "SOW signed Copilot Governance Pack",
                "No free pilot without economic signal",
                "Commercial SSOT W3 definition met",
                "Founder CRM stage Closed-Won",
                "Bank transfer or contract — no public payment SKU",
                "TrustField invoicing entity if needed internal",
                "Reject vanity logos without deposit",
                "Celebrate W3 — update tier1-status W3 row",
            ]),
            ("Referenceable board PDF in meeting (S0 proof)", [
                "Partner forwards board PDF to governance committee",
                "Founder attends or debriefs meeting outcome",
                "Capture anonymized quote ops/private",
                "No fake testimonial on www without permission",
                "Reference permission in SOW exercised",
                "Board PDF W3 milestone checked off",
                "Second partner pipeline from reference intro",
                "Investor update W3 proof paragraph",
                "Case study outline ops/private only",
                "grep testimonial on www clean until approved",
            ]),
            ("make verify-gtm full green (release discipline)", [
                "Run verify-gtm from dev-local-down fresh start",
                "All sub-scripts PASS logged",
                "Fix any regression before external demo",
                "Weekly verify-gtm founder calendar recurring",
                "Pre-tunnel verify-gtm mandatory",
                "Pre-demo verify-gtm mandatory",
                "Agent cannot skip verify-gtm",
                "CI orientation: verify-all-static on commit",
                "Document verify gate in MARKET roadmap",
                "Green verify-gtm screenshot ops/private",
            ]),
            ("make verify-www on every release (www discipline)", [
                "rebuild-www-v6.py before www release",
                "verify-no-competitor-names PASS",
                "verify-static-www comparison guard PASS",
                "No hand-edited index.html",
                "Shell v13 cache bust consistent",
                "Honest scope grid regenerated not patched",
                "Founder review diff before deploy",
                "www deploy checklist ops/private",
                "Rollback plan if verify fails post-deploy",
                "Public www never names ten vendors",
            ]),
            ("Investor page honest scarcity (capital readiness)", [
                "/investors/ hub honest scope grid",
                "Land → Expand → Channel section current",
                "Accepting design partners — scarcity real",
                "No inflated TAM stat on investor page",
                "Company compliance automation orientation row",
                "grep investor page vendor names clean",
                "Private brief links MARKET roadmap ops/private",
                "Capital map: distribution not invention",
                "Founder pitch deck aligns investor page",
                "verify-ui-e2e investors PASS",
            ]),
            ("Vancouver Trust Brief wedge live (geo W3)", [
                "Trust Brief outreach 10 Vancouver targets",
                "Healthcare OR legal accounting ICP focus",
                "First Trust Brief meeting booked",
                "Trust Brief intake form tested",
                "$10k positioning on /trust-brief/",
                "6-week deliverable deck ops/private",
                "Vancouver wedge in GTM 60-day active",
                "No global spray outreach",
                "W3 Vancouver deposit target tracked",
                "Founder weekly Vancouver pipeline review",
            ]),
            ("MSP LOI parallel track (channel W3)", [
                "Send MSP LOI to top 3 targets",
                "One MSP enablement call completed",
                "Phase 2 TLE scoped in LOI",
                "Parallel to direct design partner OK",
                "W3-MSP logged tier1-status",
                "MSP not blocking direct W3",
                "Partner demo verify-gtm green before call",
                "READINESS_TO_RECORD doc sent with LOI",
                "Follow-up cadence 7-day",
                "Channel W3 supplements not replaces direct",
            ]),
            ("Federal Trust Brief attach (regulated W3)", [
                "Federal Trust Brief outreach 3 GC contacts",
                "June 2026 ADS deadline talk track",
                "Trust Brief federal SOW variant ready",
                "Not federal certifier disclaimer in outreach",
                "AIA orientation attach only",
                "Federal W3 longer cycle — LOI counts",
                "Founder intro via warm network only",
                "No cold spray to GC departments",
                "Federal pipeline separate CRM track",
                "grep federal outreach copy buyer-safe",
            ]),
            ("Governance Monitor MRR Roadmap only (honest scale)", [
                "Governance Monitor SKU stays Roadmap badge",
                "No MRR product marketed before W3",
                "Investor honest: services + pilot now · MRR later",
                "grep Governance Monitor Shipped must fail",
                "Commercial SSOT MRR section Roadmap",
                "Drata CCM aspiration internal not product",
                "Scale follows proof not precedes",
                "Agent forbidden from building billing SKU",
                "Three SKUs unchanged at W3",
                "Post-W3 revisit Monitor orientation",
            ]),
            ("Phase X closeout — 1000 steps complete · capital ready", [
                "Review execution index all 10 phases",
                "W3 economic signal achieved or LOI signed",
                "verify-gtm + verify-all-static green",
                "MARKET_SUCCESS roadmap v3 regenerated",
                "Founder retrospective: top 10 steps that moved W3",
                "Next 1000 steps v4 planning session scheduled",
                "No vendor names leaked to www audit",
                "Investor private brief updated with W3 proof",
                "Team/agent handoff: maintain verify discipline",
                "🔒 Phase X sign-off — roadmap v3 LOCKED",
            ]),
        ],
    )


PHASE_BUILDERS = [
    ("I", "Market truth & success-model lock (10 companies × 10 steps)", company_analysis_steps),
    ("II", "Archetype A — Trust unlock (Vanta · Drata)", phase_ii_steps),
    ("III", "Archetype B — AI policy product (Credo AI · Modulos)", phase_iii_steps),
    ("IV", "Archetype C — Incumbent attach (IBM · ServiceNow · OneTrust)", phase_iv_steps),
    ("V", "Archetype D — Continuous assurance (RegScale)", phase_v_steps),
    ("VI", "Archetype E — Agentic GRC ops (Complyance · internal)", phase_vi_steps),
    ("VII", "Enterprise regulated depth (MetricStream · watsonx)", phase_vii_steps),
    ("VIII", "Channel & MSP attach (Microsoft CSP · partners)", phase_viii_steps),
    ("IX", "Receipt wedge — Noetfield product & export", phase_ix_product_steps),
    ("X", "W3 proof · scale · capital readiness", phase_x_steps),
]


def all_phases_steps() -> list[tuple[str, list[tuple[str, str, str, str]]]]:
    out = []
    for pid, title, builder in PHASE_BUILDERS:
        steps = builder()
        if len(steps) != 100:
            raise ValueError(f"Phase {pid}: expected 100 steps, got {len(steps)}")
        out.append((pid, title, steps))
    return out
