#!/usr/bin/env python3
"""Generate www chat greeting asset from data/chatbot/public-chat-greeting.json (SSOT)."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SSOT = ROOT / "data" / "chatbot" / "public-chat-greeting.json"
OUT = ROOT / "assets" / "nf-chat-greeting-ssot.js"
OUT_JSON = ROOT / "api" / "_lib" / "greeting-ssot.json"


def payload_from_ssot() -> dict[str, object]:
    data = json.loads(SSOT.read_text(encoding="utf-8"))
    greeting = str(data.get("greeting") or "").strip()
    if not greeting:
        raise SystemExit(f"FAIL: missing greeting in {SSOT}")
    citations = data.get("citations") or []
    if not isinstance(citations, list):
        raise SystemExit(f"FAIL: citations must be a list in {SSOT}")
    return {
        "schema": str(data.get("schema") or "noetfield-public-chat-greeting-v1"),
        "greeting": greeting,
        "citations": [str(c).strip() for c in citations if str(c).strip()],
    }


def content_hash(payload: dict[str, object]) -> str:
    canonical = json.dumps(
        {"greeting": payload["greeting"], "citations": payload["citations"]},
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def render_js(payload: dict[str, object], digest: str) -> str:
    body = json.dumps(
        {
            "schema": payload["schema"],
            "content_hash": digest,
            "greeting": payload["greeting"],
            "citations": payload["citations"],
        },
        ensure_ascii=True,
        indent=2,
    )
    return (
        "/* Generated by scripts/sync_chat_greeting_asset.py — do not edit. */\n"
        f"/* SSOT: data/chatbot/public-chat-greeting.json sha256={digest} */\n"
        f"window.NF_CHAT_GREETING_SSOT = {body};\n"
    )


def main() -> int:
    if not SSOT.is_file():
        print(f"FAIL: missing {SSOT}", file=sys.stderr)
        return 1
    payload = payload_from_ssot()
    digest = content_hash(payload)
    js_text = render_js(payload, digest)
    json_text = json.dumps(
        {
            "schema": payload["schema"],
            "content_hash": digest,
            "greeting": payload["greeting"],
            "citations": payload["citations"],
        },
        ensure_ascii=True,
        indent=2,
    ) + "\n"
    changed = False
    if not OUT.is_file() or OUT.read_text(encoding="utf-8") != js_text:
        OUT.write_text(js_text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} sha256={digest[:12]}")
        changed = True
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    if not OUT_JSON.is_file() or OUT_JSON.read_text(encoding="utf-8") != json_text:
        OUT_JSON.write_text(json_text, encoding="utf-8")
        print(f"wrote {OUT_JSON.relative_to(ROOT)} sha256={digest[:12]}")
        changed = True
    if not changed:
        print(f"ok unchanged greeting assets sha256={digest[:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
